### ISSUE TITLE
baksmali fails on symlinks

### ISSUE THREAD

**Issue by JesusFreke** [JesusFreke/smali#198]
Original [issue 154](https://code.google.com/p/smali/issues/detail?id=154) created by JesusFreke on 2012-11-17T16:13:57.000Z:

<b>What seems to be the problem?</b>
Under modern Windows NT, a symbolic link causes baksmali to stop processing, because a system provided file enumeration routine provides size equal to zero for symbolic links. This probably occurs in your file.exists() or file.canRead()

Symbolic links are generated by a custom tool which replaces duplicate files. Baksmali reports an error:
{
Error occured while loading boot class path files. Aborting.
org.jf.dexlib.Util.ExceptionWithContext: [...]/framework/android.policy.jar: file too short
at org.jf.dexlib.Util.ExceptionWithContext.withContext(ExceptionWithContext.java:46)
at org.jf.dexlib.Code.Analysis.ClassPath.loadBootClassPath(ClassPath.java:220)
}
Note that android.policy.jar is a symbolic link to the same, 313 bytes long file, located in another backup directory.

After replacing the symlink with the real file, baksmali runs without errors.

<b>What is the exact smali/baksmali command that you ran?</b>
java -jar /android/bin/baksmali.jar -x &quot;file.odex&quot; -d &quot;android/backup/system2.1/framework&quot; -o file.odex-smali

What version of smali/baksmali are you using? 1.2.2

**Comment by AngelaRivo** [comment]
Try to use long path tool. It will help you to shorten the file name and fix the error.
