### ISSUE TITLE
Smali Debugging -- Feedback

### ISSUE THREAD

**Issue by Fuzion24** [JesusFreke/smali#284]
I had to switch the java version that Android Studio used on OSX:

```
8:33:05 PM PluginException: org/jf/smalidea/psi/SmaliElementTypes : Unsupported major.minor version 51.0 [Plugin: org.jf.smalidea]: org/jf/smalidea/psi/SmaliElementTypes : Unsupported major.minor version 51.0 [Plugin: org.jf.smalidea]
```

```
/Applications/Android\ Studio.app/Contents/Info.plist
```
I changed
```
      <key>JVMVersion</key>
      <string>1.6*,1.7+</string>
```
to:
```
      <key>JVMVersion</key>
      <string>1.7+</string>
```

I'm seeing this error occasionally:
```
9:34:54 PM ClassCastException: org.jf.smalidea.psi.impl.SmaliClassStatement cannot be cast to com.intellij.psi.PsiModifierListOwner: org.jf.smalidea.psi.impl.SmaliClassStatement cannot be cast to com.intellij.psi.PsiModifierListOwner
```

The stepping functionality seem to be a bit wonky, but breakpoints are working well.

**Comment by Fuzion24** [comment]
Just noticed this:
Note: Single-instruction stepping is only supported in IDEA 14.1 and greater, and any future version of Android Studio based on IDEA 14.1 or greater. In earlier versions, attempting to single step will step to the next .line directive, instead of stepping to the next instruction.

This is almost certainly what I was running into.

**Comment by JesusFreke** [comment]
Thanks for the feedback! I should be able to fix the jvm version thing. For the ClassCastException, can you get the full stack trace?

**Comment by Fuzion24** [comment]
```
org.jf.smalidea.psi.impl.SmaliClassStatement cannot be cast to com.intellij.psi.PsiModifierListOwner: org.jf.smalidea.psi.impl.SmaliClassStatement cannot be cast to com.intellij.psi.PsiModifierListOwner
java.lang.ClassCastException: org.jf.smalidea.psi.impl.SmaliClassStatement cannot be cast to com.intellij.psi.PsiModifierListOwner
	at com.intellij.codeInspection.JavaSuppressionUtil.getInspectionIdsSuppressedInAnnotation(JavaSuppressionUtil.java:80)
	at com.intellij.codeInspection.JavaSuppressionUtil.getAnnotationMemberSuppressedIn(JavaSuppressionUtil.java:131)
	at com.intellij.codeInspection.JavaSuppressionUtil.getElementMemberSuppressedIn(JavaSuppressionUtil.java:119)
	at com.intellij.codeInspection.JavaSuppressionUtil$1.compute(JavaSuppressionUtil.java:221)
	at com.intellij.codeInspection.JavaSuppressionUtil$1.compute(JavaSuppressionUtil.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:921)
	at com.intellij.codeInspection.JavaSuppressionUtil.getElementToolSuppressedIn(JavaSuppressionUtil.java:199)
	at com.intellij.codeInspection.BatchSuppressManagerImpl.isSuppressedFor(BatchSuppressManagerImpl.java:45)
	at com.intellij.codeInspection.BaseJavaBatchLocalInspectionTool.isSuppressedFor(BaseJavaBatchLocalInspectionTool.java:45)
	at com.intellij.codeInspection.unusedSymbol.UnusedSymbolLocalInspectionBase.isSuppressedFor(UnusedSymbolLocalInspectionBase.java:42)
	at com.intellij.codeInspection.unusedSymbol.UnusedSymbolLocalInspectionBase.isSuppressedFor(UnusedSymbolLocalInspectionBase.java:39)
	at com.intellij.codeInspection.SuppressionUtil.inspectionResultSuppressed(SuppressionUtil.java:198)
	at com.intellij.codeInsight.daemon.impl.PostHighlightingPass.processIdentifier(PostHighlightingPass.java:271)
	at com.intellij.codeInsight.daemon.impl.PostHighlightingPass.collectHighlights(PostHighlightingPass.java:237)
	at com.intellij.codeInsight.daemon.impl.PostHighlightingPass.access$000(PostHighlightingPass.java:77)
	at com.intellij.codeInsight.daemon.impl.PostHighlightingPass$1.run(PostHighlightingPass.java:152)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.retrieveUnusedReferencesInfo(RefCountHolder.java:346)
	at com.intellij.codeInsight.daemon.impl.PostHighlightingPass.collectInformationWithProgress(PostHighlightingPass.java:149)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:380)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:371)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:368)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:193)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by JesusFreke** [comment]
Great, thanks! That should give me enough information to be able to fix it.

**Comment by JesusFreke** [comment]
I've released a new version - v0.02, which should fix both issues.

Additionally, it has new functionality that can create a new github issue with the stack trace, etc. from the error report dialog, for your reporting convenience :D

**Comment by Fuzion24** [comment]
:+1:

**Comment by imcaspar** [comment]
smalidea 0.03
android studio 1.5.1
jre: 1.6.0
running to this error again:

6:07:53 PM PluginException: org/jf/smalidea/psi/SmaliElementTypes : Unsupported major.minor version 51.0 [Plugin: org.jf.smalidea]
6:10:32 PM PicoPluginExtensionInitializationException: org/jf/smalidea/SmaliColorsPage : Unsupported major.minor version 51.0 [Plugin: org.jf.smalidea]

**Comment by tbfly** [comment]
PluginException: org/jf/smalidea/psi/SmaliElementTypes : Unsupported major.minor version 51.0 [Plugin: org.jf.smalidea]

Error comfirm!

**Comment by thearyong** [comment]
I met the same problem.

smailieda Version: 0.03
android studio 2.1.2

`org/jf/smalidea/psi/SmaliElementTypes : Unsupported major.minor version 51.0 [Plugin: org.jf.smalidea]
com.intellij.diagnostic.PluginException: org/jf/smalidea/psi/SmaliElementTypes : Unsupported major.minor version 51.0 [Plugin: org.jf.smalidea]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.psi.stubs.StubElementTypeHolderEP.initialize(StubElementTypeHolderEP.java:37)
	at com.intellij.psi.stubs.SerializationManager.initSerializers(SerializationManager.java:49)
	at com.intellij.psi.stubs.SerializationManagerImpl.serialize(SerializationManagerImpl.java:163)
	at com.intellij.psi.stubs.StubUpdatingIndex$3$1.run(StubUpdatingIndex.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:124)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.map(StubUpdatingIndex.java:118)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1671)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5600(FileBasedIndexImpl.java:99)
	at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.processFileImpl(FileBasedIndexImpl.java:2239)
	at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.access$3200(FileBasedIndexImpl.java:1865)
	at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:2288)
	at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:2285)
	at com.intellij.util.indexing.UpdateTask.process(UpdateTask.java:80)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:47)
	at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.forceUpdate(FileBasedIndexImpl.java:2220)
	at com.intellij.util.indexing.FileBasedIndexImpl$ChangedFilesCollector.access$1700(FileBasedIndexImpl.java:1865)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:834)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:801)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:242)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:223)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:135)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClassInIndex(JavaFileManagerImpl.java:122)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:115)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:124)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:101)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase$3.value(NullableStuffInspectionBase.java:161)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase$3.value(NullableStuffInspectionBase.java:158)
	at com.intellij.util.containers.ContainerUtil.find(ContainerUtil.java:883)
	at com.intellij.util.containers.ContainerUtil.find(ContainerUtil.java:854)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.nullabilityAnnotationsNotAvailable(NullableStuffInspectionBase.java:158)
	at com.intellij.codeInspection.nullable.NullableStuffInspectionBase.buildVisitor(NullableStuffInspectionBase.java:82)
	at com.intellij.codeInspection.LocalInspectionTool.buildVisitor(LocalInspectionTool.java:138)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:60)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1180)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
Caused by: java.lang.UnsupportedClassVersionError: org/jf/smalidea/psi/SmaliElementTypes : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
	... 66 more
`

**Comment by gangji001** [comment]
the same error.
![2016-07-22 8 18 12](https://cloud.githubusercontent.com/assets/1331713/17056937/842303ec-5049-11e6-8442-99c6795798a9.png)
