### ISSUE TITLE
Cant work out how to fix this

### ISSUE THREAD

**Issue by rowan23uk** [JesusFreke/smali#291]
When i try to compile with smali 2.0.0.3 i gt this error:

I: Using Apktool 2.0.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[47,4] Error for input '.p
arameter': Invalid directive
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[47,15] mismatched input '
"is"' expecting END_METHOD_DIRECTIVE
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[94,4] Error for input '.p
arameter': Invalid directive
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[95,4] Error for input '.p
arameter': Invalid directive
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[94,15] mismatched input '
"context"' expecting END_METHOD_DIRECTIVE
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file
: com/alephzain/framaroot/ycadklia.smali
        at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:71)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:371)
        at brut.androlib.Androlib.buildSources(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:282)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)

When i try with smali 1.4.3 all the files throw errors but ycadkila.

Is there a way to convert ycadkila.smali to 2.0.0.3 version???

**Comment by CalebFenton** [comment]
The smali dump was made using smali 1.x. There were a few minor changes
that broke backwards compatibility.

Compile once with 1.x, then decompile with new smali.

**Comment by JesusFreke** [comment]
What Caleb said :)
