### ISSUE TITLE
Support for FireOS 4.5.4 ODEX

### ISSUE THREAD

**Issue by jakev** [JesusFreke/smali#293]
`baksmali` fails on gen 3 Kindle Fire, with FireOS 4.5.4, framework files stored in '/system/framework/'. It fails because the magic is different than what `baksmali` expects:

```
baksmali am.odex
Exception in thread "main" org.jf.util.ExceptionWithContext: am.odex is not an apk, dex file or odex file.
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:116)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:59)
	at org.jf.baksmali.main.main(main.java:257)
```

Hex values:
```
0000000: 6465 790a 3033 3900 4000 0000 20af 0000  dey.039.@... ...
```

`file` claims:
```
file am.odex 
Dalvik dex file (optimized for host) version 039
```

`dexdump` also dislikes it:
```
dexdump am.odex 
Processing 'framework/am.odex'...
E/dalvikvm(45458): bad opt version (0x30 33 39 00)
ERROR: DEX parse failed
```

I've never seen version 39 before. Has there been any research or push for supporting this version of ODEX?

**Comment by JesusFreke** [comment]
I'm not familiar with this version. You could try tweaking the version back to 035, and seeing if baksmali will handle it, but I kinda doubt it. And without any documentation for the format, I wouldn't really be interested in trying to reverse engineer the new format to try and add support.

**Comment by jakev** [comment]
I switched it to 036, since it wants to be an ODEX file (you can see the 035 header a little further in the binary). `dexdump` actually didn't crash when i ran it ('dexdump -d -f -h -i am.odex'), but `baksmali` had some issues. Errors look like:

```
Error occurred while disassembling class Lcom.android.commands.am.Am; - skipping class
org.jf.util.ExceptionWithContext: Invalid type: V
	at org.jf.dexlib2.analysis.RegisterType.getRegisterType(RegisterType.java:238)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeMoveResult(MethodAnalyzer.java:1028)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:570)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:202)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:462)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:370)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:283)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Or:
```
org.jf.dexlib2.analysis.AnalysisException: Invalid register type (Boolean) for register v2.
    at org.jf.dexlib2.analysis.MethodAnalyzer.checkRegister(MethodAnalyzer.java:1765)
    at org.jf.dexlib2.analysis.MethodAnalyzer.getAndCheckSourceRegister(MethodAnalyzer.java:1750)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1594)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:960)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:202)
    at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137)
    at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:462)
    at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:370)
    at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
    at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:328)
    at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
    at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
    at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
    at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
    at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 230
method: Lcom/android/commands/am/Am$MyActivityController;->waitControllerLocked(II)I
```

If you want the file or any of the outputs, let me know!
