### ISSUE TITLE
some exceptions when using baksmali

### ISSUE THREAD

**Issue by Sophiexuer** [JesusFreke/smali#296]
Hi,

I use baksmali-2.0.6.jar to disassemble odex files to smali codes. However, there are some exceptions and I do not know if I make any mistake when using it. And I have already included files under /system/framework on my android device. Thank you~~ : )

org.jf.dexlib2.analysis.AnalysisException: Invalid register type (Unknown) for register v1.
	at org.jf.dexlib2.analysis.MethodAnalyzer.checkRegister(MethodAnalyzer.java:1765)
	at org.jf.dexlib2.analysis.MethodAnalyzer.getAndCheckSourceRegister(MethodAnalyzer.java:1750)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1519)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:958)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:202)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:462)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:370)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:283)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
opcode: iput-object-quick
code address: 4

Error occurred while disassembling class XXX; - skipping class
java.lang.ArrayIndexOutOfBoundsException: 7434
	at org.jf.dexlib2.analysis.AnalyzedInstruction.getPreInstructionRegisterType(AnalyzedInstruction.java:319)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeMove(MethodAnalyzer.java:1012)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:565)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:202)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:462)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:370)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:328)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)

**Comment by Sophiexuer** [comment]
By the way, I saw an old issue: http://code.google.com/p/smali/issues/detail?id=80, and I have the same log when disassembling another odex file. Is the file obfuscated?

**Comment by strazzere** [comment]
Are you sure it's skipping over code that should be disassembled? This is common in classes which obfuscators/protectors drop into the application to try and break disassemblers -- baksmali (correctly) skips over these normally. Can you provide the actual odex file?

**Comment by Sophiexuer** [comment]
Hi, 

I try to verify the cases according to https://labs.mwrinfosecurity.com/blog/2013/11/20/applovin-ad-library-sdk-remote-command-execution-via-update-mechanism/ and https://www.nowsecure.com/blog/2015/06/16/remote-code-execution-as-system-user-on-samsung-phones/. And I use some normal apps, such as Highmoralmap, qq brower and some other apps, to find out if there are any vulnerabilities. However, when I disassembled their odex files, I got the exceptions above. So I wonder how the researchers insert or modify codes to fake odex files which will be used by apps.

And I only know some sample method to obfuscate apps. So I could not image how the methods could make such a challenge to disassembling.

Could you give me some suggestions or references about the two points?

Thank you~~ : )

**Comment by JesusFreke** [comment]
What device and version of android are the odex files from?

**Comment by Sophiexuer** [comment]
HI,

I use MX3(Flyme OS 3.0.2) and its Android version is 4.2.1.

**Comment by JesusFreke** [comment]
After a second look, those sound like normal non-system apps. Are you downloading and installing those apps from the play store (and/or other source), or are they bundled on the system partition of the device?

If the former, there's no need to deodex them. Just run baksmali on the apk. If the latter, it's likely some form of apk obfuscation, as strazzere suggested.

**Comment by Sophiexuer** [comment]
Well, I know.

The files are from /data/data/packagename/ directory of the apps.

Thank you~~

**Comment by JesusFreke** [comment]
If it's not a system app on a pre-odexed system image, then you should be able to get the original dex file, instead of trying to deodex the odex file. And /data/data/packagename/ doesn't typically contain any odex files, although it's possible the app is dynamically loading a dex file and specifying their own dalvik-cache location inside of /data/data/packagename. But even then, the dex file should be available.

Deodexing is primarily needed for pre-odexed system images, where *only* the odex file is available, and the original dex file is simply not present on the device.
