### ISSUE TITLE
Baksmali errors

### ISSUE THREAD

**Issue by LostAngel** [JesusFreke/smali#297]
java.lang.Exception: could not exec command: [java, -Xms4057m, -Xmx4057m, -jar, /home/su/image/ARSC/aApps/libs/smali-2.0.7-557a9976-small.jar, /home/su/image/ARSC/ARSCWorker_n9005_bhflower_5.6.26/smali_temp_framework, -o, /home/su/image/ARSC/ARSCWorker_n9005_bhflower_5.6.26/classes_build_framework.dex, -a, 19]
com.android.dex.DexIndexOverflowException: Cannot merge new index 65536 into a non-jumbo instruction!
at com.android.dx.merge.InstructionTransformer.jumboCheck(Unknown Source)
at com.android.dx.merge.InstructionTransformer.access$800(Unknown Source)
at com.android.dx.merge.InstructionTransformer$StringVisitor.visit(Unknown Source)
at com.android.dx.io.CodeReader.callVisit(Unknown Source)
at com.android.dx.io.CodeReader.visitAll(Unknown Source)
at com.android.dx.merge.InstructionTransformer.transform(Unknown Source)
at com.android.dx.merge.DexMerger.transformCode(Unknown Source)
at com.android.dx.merge.DexMerger.transformMethods(Unknown Source)
at com.android.dx.merge.DexMerger.transformClassData(Unknown Source)
at com.android.dx.merge.DexMerger.transformClassDef(Unknown Source)
at com.android.dx.merge.DexMerger.mergeClassDefs(Unknown Source)
at com.android.dx.merge.DexMerger.mergeDexes(Unknown Source)
at com.android.dx.merge.DexMerger.merge(Unknown Source)

**Comment by JesusFreke** [comment]
This has nothing to do with smali/baksmali. This is a dx error.
