### ISSUE TITLE
Could not decompile huawei rom

### ISSUE THREAD

**Issue by zhouchaohong1111** [JesusFreke/smali#298]
When I decompile HwFloatMms.odex from huaweirom Honor-3C-H30-U10-Dalet11-KitKat-V2.5-EMUI-3.0,

you can download from:
http://bsp.needrom.com/2015/02/Honor-3C-H30-U10-Dalet11-KitKat-V2.5-EMUI-3.0.zip

java -jar E:/development
/smali-2.0.6/baksmali.jar -x ./app/HwFloatMms.odex -d ./framework -o ./out/odex/
HwFloatMms

Error occurred while disassembling class Lcom.google.common.math.DoubleMath; - s
kipping class
java.lang.RuntimeException: Invalid method index: 29
        at org.jf.dexlib2.analysis.InlineMethodResolver$InlineMethodResolver_ver
sion36.resolveExecuteInline(InlineMethodResolver.java:175)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeExecuteInline(MethodAna
lyzer.java:1422)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnaly
zer.java:941)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:20
2)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137
)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMetho
dItems(MethodDefinition.java:462)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefini
tion.java:370)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.ja
va:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefi
nition.java:283)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:112)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

some other huawei rom has the same issue.

**Comment by JesusFreke** [comment]
baksmali does not support L+ odexes. I'll be adding support for M+ odexes soon, but L odexes will not be supported due to certain technical limitations. See issue 269 for more info

**Comment by JesusFreke** [comment]
Oh, I'm sorry - I just realized this is a kitkat rom, not L :)

**Comment by JesusFreke** [comment]
This particular problem is likely caused by a non-standard inline method table. You can use deodexerant to dump the inline method table from the device, and then pass it to baksmali with the -T option (use baksmali -?? (2 ?'s) for info on the -T option)

**Comment by JesusFreke** [comment]
You can find deodexerant here:  https://github.com/JesusFreke/smali/tree/master/deodexerant

**Comment by zhouchaohong1111** [comment]
@JesusFreke  could you give me a runnable deodexerant on ubuntu, and tell me how can i use it if i only own the rom file not a phone.  the link you give only source file.

**Comment by JesusFreke** [comment]
The link has instructions for building it :)
