### ISSUE TITLE
Error while disassembing class

### ISSUE THREAD

**Issue by acgmohu** [JesusFreke/smali#307]
Hi,

Today I found some samples which can crash baksmali-2.0.6 and smali-2.0.6.
Here is the dex file.
  
    http://yunpan.cn/cHK5bzcGJbncN  访问密码 07d3

baksmali
```   
Error occurred while disassembling class Landroid.support.v4.net.TrafficStatsCompat; - skipping class
org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0xbdc3c
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:52)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation.getDebugInfo(DexBackedMethodImplementation.java:126)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation.getParameterNames(DexBackedMethodImplementation.java:136)
        at org.jf.dexlib2.dexbacked.DexBackedMethod.getParameterNames(DexBackedMethod.java:153)
        at org.jf.dexlib2.dexbacked.DexBackedMethod$1.iterator(DexBackedMethod.java:131)
        at java.util.AbstractCollection.toArray(Unknown Source)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258)
        at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:93)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```

smali 
```
out\A001.smali[10,0] mismatched input '' expecting END_METHOD_DIRECTIVE
out\a\a\a\a.smali[13,0] mismatched input '' expecting END_METHOD_DIRECTIVE
out\android\content\pm\IPackageDataObserver$Stub.smali[18,0] mismatched input '' expecting END_METHOD_DIRECTIVE
out\a\a\a\c.smali[9,0] mismatched input '' expecting END_METHOD_DIRECTIVE
out\android\content\pm\IPackageManager$Stub.smali[18,0] mismatched input '' expecting END_METHOD_DIRECTIVE
out\android\content\pm\PackageDataObserver.smali[12,0] mismatched input '' expecting END_METHOD_DIRECTIVE
out\android\content\pm\IPackageStatsObserver$Stub.smali[18,0] mismatched input '' expecting END_METHOD_DIRECTIVE
out\android\content\pm\PackageManager$NameNotFoundException.smali[9,0] mismatched input '' expecting END_METHOD_DIRECTIVE
```

**Comment by JesusFreke** [comment]
This is fixed by 4d8ec4c7, in smali/baksmali v2.0.8
