### ISSUE TITLE
Deodexing telephony-common.jar from stock hammerhead mra58k firmware fails

### ISSUE THREAD

**Issue by andreya108** [JesusFreke/smali#314]
used version 2.1.0, new marshmallow deodexing feature works for all other boot.oat enties, except telephony-common.jar:

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Lcom/android/internal/telephony/cdma/CdmaServiceStateTracker; at offset 253
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1557)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:981)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: iget-boolean-quick
code address: 199
method: Lcom/android/internal/telephony/cdma/CdmaServiceStateTracker;->dump(Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Lcom/android/internal/telephony/gsm/GsmServiceStateTracker; at offset 222
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1557)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:981)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: iget-boolean-quick
code address: 271
method: Lcom/android/internal/telephony/gsm/GsmServiceStateTracker;->dump(Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V

**Comment by JesusFreke** [comment]
Can you try it with the latest source? I have a few changes in after 2.1.0 that might have fixed it. If so, I'll go ahead and put out a 2.1.1 to get the fix out.

**Comment by andreya108** [comment]
Yes! It seems that in the latest sources (2.1.0-ccf087b0-dirty) the problem has gone!
So, looking forward to 2.1.1!
