### ISSUE TITLE
boot.oat in Nexus 6 Marshmallow is v39

### ISSUE THREAD

**Issue by superr** [JesusFreke/smali#315]
Hello. Thank you for your work and support. Testing v2.1.0 with the Nexus 6 Marshmallow release found here:
https://dl.google.com/dl/android/aosp/shamu-mra58k-factory-5b07088c.tgz

Here is the result.

superr@studio:~/shamu_M/system/framework/arm$ java -jar ~/bin/baksmali.jar boot.oat
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedOatVersionException: Unsupported oat version: 39
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:147)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
	at org.jf.baksmali.main.main(main.java:266) 

Thanks again :)

**Comment by superr** [comment]
My bad. I got the files confused somehow and that was a Lollipop boot.oat. Thanks again for your work. It is very much appreciated :)
