### ISSUE TITLE
Trouble deodexing KK

### ISSUE THREAD

**Issue by superr** [JesusFreke/smali#319]
Hello, it's me again. Using your newest source 37d14be, I have issues with several apps and framework in KitKat.

Here is the zip containing all the problem apps and the entire framework:

https://s.basketbuild.com/dlgate/devs?dev=SuperR&dl=SuperR/Testing/warplte_KK_test.zip

Here is a link to the output from my script:

http://hastebin.com/uducamuwoj.avrasm

As you will see, many of the apps and framework deodexed so I don't think it is a problem with my syntax. 

I really appreciate your time :)

**Comment by JesusFreke** [comment]
Nothing should have changed for KK. Do you encounter the same problem if you use baksmali v2.0.8 to deodex?

**Comment by JesusFreke** [comment]
Also, please provide the actual command lines used for each invocation, in the script output.

**Comment by superr** [comment]
I am so sorry for not providing the command. Here it is:
```
superr@studio:~/android/Warp_4G/system/app$ java -jar ~/bin/baksmali.jar -a 19 -d ../framework -x Calculator_ZTE.odex -o smali


Error occurred while disassembling class Landroid.support.v4.content.ModernAsyncTask; - skipping class
java.lang.RuntimeException: Unexpected opcode: sput-object-volatile
	at org.jf.dexlib2.analysis.OdexedFieldInstructionMapper.isCompatible(OdexedFieldInstructionMapper.java:205)
	at org.jf.dexlib2.analysis.OdexedFieldInstructionMapper.getAndCheckDeodexedOpcode(OdexedFieldInstructionMapper.java:194)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzePutGetVolatile(MethodAnalyzer.java:1840)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzePutGetVolatile(MethodAnalyzer.java:1831)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1020)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
superr@studio:~/android/Warp_4G/system/app$
```
I used the exact same syntax for every app that has the errors. 

I will check the funtionality using v2.0.8. Just need to find it first. If I don't see it I will compile from your source. Thanks again for the support :)

**Comment by superr** [comment]
I complied your v2.0.8 and there are no errors running the exact same command
```
superr@studio:~/android/Warp_4G/system/app$ java -jar ~/bin/baksmali-2.0.8.jar -a 19 -d ../framework -x Calculator_ZTE.odex -o smali
```

**Comment by JesusFreke** [comment]
There were a few issues here. Try with the latest source :)

**Comment by superr** [comment]
Thank you so much. You are greatly appreciated :)
