### ISSUE TITLE
Trouble deodexing M 64-bit

### ISSUE THREAD

**Issue by superr** [JesusFreke/smali#320]
Hello again. More trouble with M, 64-bit this time. Testing on Nexus 9. Using your latest commit 37d14be

Here is a zip with the framework/arm/boot.oat and framework/arm64/boot.oat:
https://s.basketbuild.com/dlgate/devs?dev=SuperR&dl=SuperR/Testing/volantis_M_test.zip

From the arm64 directory:
```
superr@studio:~/android/volantis/system/framework/arm64$ java -jar ~/bin/baksmali.jar boot.oat
Exception in thread "main" org.jf.dexlib2.dexbacked.OatFile$InvalidOatFileException: Oat file has no symbol table
	at org.jf.dexlib2.dexbacked.OatFile.getSymbolTable(OatFile.java:290)
	at org.jf.dexlib2.dexbacked.OatFile.<init>(OatFile.java:76)
	at org.jf.dexlib2.dexbacked.OatFile.fromInputStream(OatFile.java:124)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:140)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
	at org.jf.baksmali.main.main(main.java:266)
```
The same command from the arm directory works as expected:
```
superr@studio:~/android/volantis/system/framework/arm$ java -jar ~/bin/baksmali.jar boot.oat
boot.oat contains multiple dex files. You must specify which one to disassemble with the -e option
Valid entries include:
/system/framework/core-libart.jar
/system/framework/conscrypt.jar
/system/framework/okhttp.jar
/system/framework/core-junit.jar
/system/framework/bouncycastle.jar
/system/framework/ext.jar
/system/framework/framework.jar
/system/framework/framework.jar:classes2.dex
/system/framework/telephony-common.jar
/system/framework/voip-common.jar
/system/framework/ims-common.jar
/system/framework/apache-xml.jar
/system/framework/org.apache.http.legacy.boot.jar
```
Thanks again for your time and support :)

**Comment by JesusFreke** [comment]
Should be fixed by b8e255f3

**Comment by superr** [comment]
Awesome! Thank you so much :) 

Now I am a bit confused and hope you can shed some light. Since there is an arm and arm64 boot.oat, which one should I use to deodex framework? They both contain dex files for the same files in framework.

**Comment by JesusFreke** [comment]
They should be equivalent. Take your pick :)

**Comment by superr** [comment]
Nice, thank you so much :)
