### ISSUE TITLE
"Invalid stub element type in index" in SmaliClassTypeElement.resolve

### ISSUE THREAD

**Issue by SmalideaIssueReporter** [JesusFreke/smali#336]
protocol.version: 1
os.name: Mac OS X
java.version: 1.8.0_25
java.vm.vendor: Oracle Corporation
app.name: IDEA
app.name.full: IntelliJ IDEA
app.name.version: IntelliJ IDEA
app.eap: false
app.internal: false
app.build: IU-141.1010
app.version.major: 14
app.version.minor: 1.3
app.build.date: 1431360000000
app.build.date.release: 1427040000000
app.compilation.timestamp: null
update.channel.status: release
update.ignored.builds: 
plugin.name: Smalidea
plugin.version: 0.02
last.action: null
previous.exception: null
assignee.id: null

```
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
    at com.intellij.psi.stubs.StubIndexImpl.reportStubPsiMismatch(StubIndexImpl.java:534)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:155)
    at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
    at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
    at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.a(JavaFileManagerImpl.java:145)
    at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:138)
    at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
    at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:102)
    at org.jf.smalidea.psi.impl.SmaliClassTypeElement.resolve(SmaliClassTypeElement.java:99)
    at org.jf.smalidea.psi.impl.SmaliFieldReference.getContainingClass(SmaliFieldReference.java:63)
    at org.jf.smalidea.psi.impl.SmaliFieldReference.resolve(SmaliFieldReference.java:113)
    at org.jf.smalidea.psi.impl.SmaliFieldReference.isReferenceTo(SmaliFieldReference.java:127)
    at com.intellij.psi.search.SingleTargetRequestResultProcessor.processTextOccurrence(SingleTargetRequestResultProcessor.java:50)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$17.execute(PsiSearchHelperImpl.java:765)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.a(LowLevelSearchUtil.java:126)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:200)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3$1.compute(PsiSearchHelperImpl.java:214)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3$1.compute(PsiSearchHelperImpl.java:211)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:884)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:211)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:208)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$16.process(PsiSearchHelperImpl.java:729)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$16.process(PsiSearchHelperImpl.java:723)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.compute(PsiSearchHelperImpl.java:371)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.compute(PsiSearchHelperImpl.java:356)
    at com.intellij.openapi.application.ex.ApplicationUtil$1.run(ApplicationUtil.java:37)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
    at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:34)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.a(PsiSearchHelperImpl.java:356)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.access$000(PsiSearchHelperImpl.java:68)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:304)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:299)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:211)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:211)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:211)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
    at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:211)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:449)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

```

```
Invalid stub element type in index:
file: file:///Users/yuyang/Documents/Kara/com.tencent.karaoke/src/com/tencent/karaoke/module/qrc/business/m.java
psiElement: PsiImportStatement
requiredClass: interface com.intellij.psi.PsiClass
actualClass: class com.intellij.psi.impl.source.PsiImportStatementImpl
virtualFile: size:5586; stamp:0; modCount:1445588116000; fileType:JAVA; language:JAVA
document: size:5586; stamp:0; committed:true; saved:true
psiFile: size:5586; stamp:0; class:com.intellij.psi.impl.source.PsiJavaFileImpl; language:JAVA
fileAST: size:5586; parsed:true
indexing info: indexed at 1445588116000 with size 5586
```

**Comment by JesusFreke** [comment]
Copied to https://github.com/JesusFreke/smalidea-issues/issues/217
