### ISSUE TITLE
Problem deodexing 5.1.1 arm

### ISSUE THREAD

**Issue by DavidMKD** [JesusFreke/smali#349]
Hello. I've been trying to deodex the services.jar file for several times on 5.1.1 but no luck so far.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1282473125
        at org.jf.dexlib2.dexbacked.BaseDexReader.readUleb128(BaseDexReader.java:101)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readSmallUleb128(BaseDexReader.java:92)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:86)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:141)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
        at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
        at java.util.AbstractCollection.toArray(Unknown Source)
        at com.google.common.collect.Iterables.toArray(Iterables.java:328)
        at com.google.common.collect.Ordering.sortedCopy(Ordering.java:816)
        at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:135)
        at org.jf.baksmali.main.main(main.java:305)

**Comment by JesusFreke** [comment]
Not enough information. Feel free to reopen if you're still having this issue.
