### ISSUE TITLE
Error when regeneration dex from smali with unicode file name

### ISSUE THREAD

**Issue by hieunp8x** [JesusFreke/smali#350]
Dear you,
When i try decode to smali then **regeneration dex file from smali, I gave error FileNotFoundException with unicode class file name** , I thing maybe reason is class name is unicode. <br>
Original classes.dex file locate at https://drive.google.com/open?id=0BzD1w7jyro1_SlFHUC14cm5XWnc
#### My Environment
+ MacOSX 64 bit (Elcapital)
+ Java: 1.8.0_60 (64 bit)
+ Smali version 2.1.0

### I did via 2 steps
1. **Step1**: Decode to smali no problem <br>
` baksmali -o classes_smali classes.dex `
2. **Step2**: Generate dex from decoded smali source <br>
    get error **"FileNotFoundException classes_smali/o/K.2.smali (No such file or directory)"**<br>
` smali classes_smali -o classes.dex `<br>
error detail as<br>
` UNEXPECTED TOP-LEVEL ERROR:
java.util.concurrent.ExecutionException: java.io.FileNotFoundException: /Users/el/classes_smali/o/K.2.smali (No such file or directory)
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.jf.smali.main.main(main.java:243)
Caused by: java.io.FileNotFoundException: /Users/el/classes_smali/o/K.2.smali (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at org.jf.smali.main.assembleSmaliFile(main.java:330)
        at org.jf.smali.main.access$000(main.java:58)
        at org.jf.smali.main$1.call(main.java:234)
        at org.jf.smali.main$1.call(main.java:232)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`<br><br>
Please help me and tell me why?<br>
Thanks!

**Comment by JesusFreke** [comment]
Hmm. I'm not able to reproduce this on linux, and I don't have access to a Mac environment for testing.

I've added a speculative fix in 73bd8ce9. Can you do a build from the latest source and see if it's working for you now?

**Comment by hieunp8x** [comment]
I've been build with source code and test again on MAC, but still occurred above error. --> **I think that is problem of MAC OS** because on Linux don't occurred this error. So close this issue at here.

**Comment by hieunp8x** [comment]
I've tested on Linux, it occurred another error. I posted bug on [356] (https://github.com/JesusFreke/smali/issues/353).
