### ISSUE TITLE
Could not decode arsc file - Samsung TW Android M 6.0

### ISSUE THREAD

**Issue by ManhIT-CMB** [JesusFreke/smali#361]
H:\ApkTool_2.0.2_New>apktool.bat if H:\M_Bets_S6\G920F\system\framework\framework-res.apk
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:599)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:581)
        at brut.androlib.Androlib.installFramework(Androlib.java:676)
        at brut.apktool.Main.cmdInstallFramework(Main.java:240)
        at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:254)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:203)
        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)

**Comment by JesusFreke** [comment]
You should file this on the apktool project :)

https://github.com/iBotPeaches/Apktool/issues
