### ISSUE TITLE
GmsCore.odex deodexing error

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#364]
Hi JesusFreke
When i try to deodexing GmsCore.odex, i get a lot of errors like

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Lcom/d/a/c; at index 12
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1784)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1009)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:205)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:140)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 58
method: Lc/a/c/p;-><clinit>()V

I use command:
java  -Xmx512m -jar baksmali-2.1.1.jar -x -c boot.oat -d "_framework\arm" -e "/system/priv-app/GmsCore/GmsCore.apk" "_app\GmsCore\oat\arm\GmsCore.odex" -o "_app\GmsCore\oat\arm\GmsCore\classes" 

Here is GmsCore.odex and boot.oat:
https://yadi.sk/d/mI2oY40_mpbKi

Thanks!

**Comment by JesusFreke** [comment]
This occurs when the app odex file has multiple dex files that are interdependent. If you add the app odex file to the classpath, baksmali will add all of the dex files for that application to the classpath.

e.g.

baksmali -x -c boot.oat:GmsCore.odex   -d _framework/arm -d _app/GmsCore/oat/arm -e /system/priv-app/GmsCore/GmsCore.apk _app/GmsCore/oat/arm/GmsCore.odex

**Comment by bursoft-git** [comment]
JesusFreke, thank you, it works!

Another question:
How can I find out how many classes*.dex are in a *.odex without disassembling it?

For example, "java -jar baksmali-2.1.1.jar GmsCore.odex" output is:
GmsCore.odex contains multiple dex files. You must specify which one to disassemble with the -e option
Valid entries include:
/system/priv-app/GmsCore/GmsCore.apk
/system/priv-app/GmsCore/GmsCore.apk:classes2.dex
/system/priv-app/GmsCore/GmsCore.apk:classes3.dex

But, for "java -jar baksmali-2.1.1.jar TimeService.odex" output is:
Warning: You are disassembling an odex file without deodexing it. You won't be able to re-assemble the results unless you deodex it with the -x option
AND "out" folder with disassembled *.smali files.

In my batch deodex tool "Batch Apktool" it wery slows deodexing process.

**Comment by imadlatch** [comment]
not working for me 
Exception in thread "main" org.jf.util.ExceptionWithContext: GmsCore.odex is not an apk, dex file or odex file.
        at org.jf.dexlib2.DexFileFactory.loadDexFiles(DexFileFactory.java:140)
        at org.jf.dexlib2.DexFileFactory.loadDexFiles(DexFileFactory.java:81)
        at org.jf.baksmali.main.main(main.java:259)

**Comment by JesusFreke** [comment]
@imadlatch That error has nothing to do with this closed issue. But feel free to file a new issue

**Comment by imadlatch** [comment]
oh I didn't notice 
The issue related with oat2dex.jar
I think my mistake is  java -jar oat2dex.jar GmsCore.odex dex
it should be  java -jar oat2dex.jar odex GmsCore.odex 

am I right ?

**Comment by JesusFreke** [comment]
This still has nothing to do with this closed issue. And oat2dex.jar is not a part of smali/baksmali.

**Comment by imadlatch** [comment]
I'm trying to deodex GmsCore.odex with baksmali.jar I got error
java -jar baksmali.jar -x GmsCore.odex
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.io.ByteArrayOutputStream.grow(Unknown Source)
        at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
        at java.io.ByteArrayOutputStream.write(Unknown Source)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:74)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:115)
        at org.jf.dexlib2.dexbacked.OatFile.fromInputStream(OatFile.java:132)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:140)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
        at org.jf.baksmali.main.main(main.java:292)

I don't fully understand the example above
can you explain it Please?

baksmali -x -c boot.oat:GmsCore.odex -d _framework/arm -d _app/GmsCore/oat/arm -e /system/priv-app/GmsCore/GmsCore.apk _app/GmsCore/oat/arm/GmsCore.odex

**Comment by imadlatch** [comment]
as the example

java -jar baksmali.jar -x -c boot.oat:GmsCore.odex -d framework\x86 -d priv-app\GmsCore\x86 -e priv-app\GmsCore\GmsCore.apk GmsCore.odex
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.io.ByteArrayOutputStream.grow(Unknown Source)
        at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
        at java.io.ByteArrayOutputStream.write(Unknown Source)
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:74)
        at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:115)
        at org.jf.dexlib2.dexbacked.OatFile.fromInputStream(OatFile.java:132)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:140)
        at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
        at org.jf.baksmali.main.main(main.java:292)

**Comment by JesusFreke** [comment]
@imadlatch please file a new issue, unless you're seeing the same error as in this issue.
