### ISSUE TITLE
Error during disassembling boot-framework.oat (Android N)

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#378]
Hi JesusFreke!

When im trying deodex boot-framework.oat from Android N (http://developer.android.com/intl/ru/preview/download.html), i got an error:
```
c:\BatchApkTool>java -jar baksmali.jar _framework\arm\boot-framework.oat
boot-framework.oat contains multiple dex files. You must specify which one to disassemble with the -e option
Valid entries include:
/system/framework/framework.jar
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1604185043
        at java.lang.String.checkBounds(String.java:375)
        at java.lang.String.<init>(String.java:452)
        at org.jf.dexlib2.dexbacked.OatFile$1$1.next(OatFile.java:172)
        at org.jf.dexlib2.dexbacked.OatFile$1$1.next(OatFile.java:159)
        at org.jf.baksmali.main.main(main.java:298)
```

Full framework folder with boot-framework.oat here https://yadi.sk/d/j_TA-IuIqHLzo

Thanks!

**Comment by JesusFreke** [comment]
Yep, there were some changes to the oat format in the version of art used by N. I've started adding support for new version of art.

**Comment by mrtowel** [comment]
So how is it going with Android N? 

I'm getting a exception: 

```
$ java -jar baksmali-2.1.3.jar -x -c boot.oat -d framework service.odex -o out


Error occurred while loading boot class path files. Aborting.
org.jf.util.ExceptionWithContext: Cannot locate boot class path file boot.oat
	at org.jf.dexlib2.analysis.ClassPath.loadClassPathEntry(ClassPath.java:277)
	at org.jf.dexlib2.analysis.ClassPath.fromClassPath(ClassPath.java:182)
	at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:67)
	at org.jf.baksmali.main.run(main.java:113)
	at org.jf.baksmali.main.main(main.java:322)
```

**Comment by JesusFreke** [comment]
@mrtowel That error has nothing to do with N support. (hint: there is no boot.oat directly in the framework directory) But N isn't supported yet anyway :)

**Comment by JesusFreke** [comment]
v2.2b1 now supports deodexing oat files from N
