### ISSUE TITLE
regression in release 2.1.2 (jflex plugin incompatbile with gradle 2.12)

### ISSUE THREAD

**Issue by anthraxx** [JesusFreke/smali#393]
Hi I'm the maintainer of smali and noticed a regression during update so i can't ship your new version.
I'm using the latest gradle-2.12-1

when invoking the gradle build i get the following error:

    FAILURE: Build failed with an exception.
    
    * Where:
    Build file '/build/smali/src/smali-2.1.2/smali/build.gradle' line: 33
    
    * What went wrong:
    A problem occurred evaluating project ':smali'.
    > org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;)V
    
    * Exception is:
    org.gradle.api.GradleScriptException: A problem occurred evaluating project ':smali'.
    	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
    	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScriptPluginFactory.java:155)
    	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
    	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:160)
    	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
    	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
    	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
    	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:532)
    	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:93)
    	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
    	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
    	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
    	at org.gradle.internal.Factories$1.create(Factories.java:22)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
    	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.file.DefaultSourceDirectorySet.<init>(Ljava/lang/String;Lorg/gradle/api/internal/file/FileResolver;)V
    	at co.tomlee.gradle.plugins.jflex.JFlexVirtualSourceDirectoryImpl.<init>(JFlexVirtualSourceDirectoryImpl.java:14)
    	at co.tomlee.gradle.plugins.jflex.JFlexPlugin$1.execute(JFlexPlugin.java:47)
    	at co.tomlee.gradle.plugins.jflex.JFlexPlugin$1.execute(JFlexPlugin.java:39)
    	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
    	at co.tomlee.gradle.plugins.jflex.JFlexPlugin.configureSourceSets(JFlexPlugin.java:39)
    	at co.tomlee.gradle.plugins.jflex.JFlexPlugin.apply(JFlexPlugin.java:31)
    	at co.tomlee.gradle.plugins.jflex.JFlexPlugin.apply(JFlexPlugin.java:18)
    	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
    	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
    	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:137)
    	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
    	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
    	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
    	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
    	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
    	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
    	at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
    	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
    	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
    	at build_b85mvysfpqvernutfvf0lsyvk.run(/build/smali/src/smali-2.1.2/smali/build.gradle:33)
    	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    	... 58 more
    
    
    BUILD FAILED
    
    Total time: 9.144 secs
    Stopped 0 compiler daemon(s).
    Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Build file '/build/smali/src/smali-2.1.2/smali/build.gradle' line: 33
    A problem occurred evaluating project ':smali'.] from daemon DaemonInfo{pid=500, address=[31f11dc3-c9ef-4f0d-bc5f-967d67c35051 port:35282, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]], idle=false, context=DefaultDaemonContext[uid=57254ec1-4fb5-4fd1-bb3f-33d24863e4f7,javaHome=/usr/lib/jvm/java-8-openjdk,daemonRegistryDir=/build/smali/src/smali-2.1.2/daemon,pid=500,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=US-ASCII,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).

**Comment by JesusFreke** [comment]
Hmm. This looks like an issue with the jflex plugin and the newest version of gradle.

**Comment by JesusFreke** [comment]
Per the build.gradle, the build for smali should be done using gradle 2.11.

**Comment by anthraxx** [comment]
@JesusFreke thats not how builds on a distribution level can be made unfortunately. I will create a bug report for the jflex plugin and you could bump it once its fixed maybe?

**Comment by JesusFreke** [comment]
Yep, I'll be happy to bump the gradle version once jflex is fixed

**Comment by anthraxx** [comment]
I created the referenced bug ticket for the plugin that you are using, hopefully he will resolve it fast :smile: 
Purely a fun fact: When google-ing for the plugin, I also found a similar named one that fixed 2.12 things: https://github.com/jprante/gradle-plugin-jflex

**Comment by anthraxx** [comment]
@JesusFreke just in case you missed it and for the logs in this ticket: @thomaslee has proposed to maybe consider changing to the other plugin instead as he maybe does not like to duplicate efforts. https://github.com/thomaslee/gradle-jflex-plugin/pull/4#issuecomment-214103007

**Comment by JesusFreke** [comment]
Yep, I saw. I'm planning on moving things over. Thanks!

**Comment by anthraxx** [comment]
fine, no rush just wanted to make sure you don't miss it :smile:

**Comment by anthraxx** [comment]
hm, any update? Really looking forward to get a new version into the distribution :smile_cat:

**Comment by JesusFreke** [comment]
I'll definitely get it into the next version, which I think I should be finishing up soon.

**Comment by anthraxx** [comment]
could you solve this and change the dependency to the other one? I would like to see if i can backport the patch then, feels bad that i could still not do my package maintainer job and update the package :cat:

**Comment by JesusFreke** [comment]
I've updated smali to use gradle 2.14 and jprante's plugin.

I was planning on just rolling this into the 2.2 release, but I haven't had time to finish up the work on the new CLI yet, so I'll just went ahead and put it in the current branch, and I'll do a new minor release for this and some other minor fixes.
