### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Nieo-Hacker** [JesusFreke/smali#396]
Error:-

Exception in thread "main" Exception in thread "pool-1-thread-1" java.lang.NullPointerException: 
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.compareAndSetState(AbstractQueuedSynchronizer.java:566)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:211)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
	at java.util.concurrent.ThreadPoolExecutor.interruptIdleWorkers(ThreadPoolExecutor.java:781)
	at java.util.concurrent.ThreadPoolExecutor.interruptIdleWorkers(ThreadPoolExecutor.java:806)
	at java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1392)
	at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:171)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:85)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:94)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:131)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
java.lang.NullPointerException: 
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.compareAndSetState(AbstractQueuedSynchronizer.java:566)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:211)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:998)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1163)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
I: Using Apktool 2.1.0 on xxxxx.apk
I: Copying raw resources...
I: Baksmaling classes.dex...

Strange but I decompile & recompile same apk few minutes before but when I try to decompile all again it throw above exception & after that same exception I getting when I m trying to decompile any other apk file..

OS use:- Xperia Miro 4.04
Apktool:- 2.10
Small:- 2.10
Baksmali:- 2.10

**Comment by JesusFreke** [comment]
Does this happen when you use the the latest version of baksmali (2.1.2) to disassemble the apk?

**Comment by Nieo-Hacker** [comment]
[2016-04-14-00-19-31.txt](https://github.com/JesusFreke/smali/files/217792/2016-04-14-00-19-31.txt)

I attached locate 

How to reproduce error:-
When I try to recompile "ODEX"

Yes same result with 
Smali :- 2.1.2
Baksmali :- 2.1.2
Apktool :- 2.1.0

**Comment by JesusFreke** [comment]
This looks like a problem with your device. This NPE is from within the platform AbstractQueuedSynchronizer class, and it looks like that object's internal Unsafe object is null for some reason. baksmali has no way to affect or fix this.

**Comment by Nieo-Hacker** [comment]
Yes you are correct :)

I further debug and trace reason ..
It's my device..

Putting task activity in background solved the issue..

Thanks for your answer & Time.. :)
