### ISSUE TITLE
General message for unknown label

### ISSUE THREAD

**Issue by Enyby** [JesusFreke/smali#399]
If we use label not placed we got error message:
```
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalStateException: Cannot get the location of a label that hasn't been placed yet.
        at org.jf.dexlib2.builder.Label.getLocation(Label.java:54)
        at org.jf.dexlib2.builder.Label.getCodeAddress(Label.java:48)
        at org.jf.dexlib2.builder.BuilderOffsetInstruction.internalGetCodeOffset(BuilderOffsetInstruction.java:60)
        at org.jf.dexlib2.builder.BuilderOffsetInstruction.getCodeOffset(BuilderOffsetInstruction.java:50)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:206)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:988)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:803)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:252)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:230)
        at org.jf.smali.main.run(main.java:176)
        at org.jf.smali.main.main(main.java:265)
```
This message do not contains label name. This is very hard to fix because in file we have thousand of labels.
I think better can be get name of unexists label. Something like:
```
java.lang.IllegalStateException: Cannot get the location of a label (:goto_ba) that hasn't been placed yet.
```

**Comment by Enyby** [comment]
In additional good be know not only label. We need file and method for this label. Perfect be file + line from bugged instruction. If it is possible.

**Comment by JesusFreke** [comment]
Labels don't have a name associated with them at the dexlib2 level. And you obviously can't use the label address for this, because it's not named.

An unplaced label won't be associated with a class yet either.

I definitely agree the error isn't very useful as-is and should be improved. In this case, I think adding context information from the CodeItem (i.e.the class/method/address of the instruction being written when the error occurs) is probably the best option.

**Comment by Storyyeller** [comment]
Why not keep track of the source locations of the relevant token so you can output a more informative error message?

**Comment by JesusFreke** [comment]
This is an error you should only see if you're using dexlib2 directly, and you try to use a label without actually specifying the location of the label. In this case "label" is a concept (i.e. a class) in dexlib2, and has nothing to do with labels in smali (other than the fact that smali labels actually use dexlib2 labels under the hood). Smali (the language, and the program) isn't involved at all, so there are no tokens.

**Comment by JesusFreke** [comment]
Actually, it looks like this *is* using smali, based on the stacktrace. @Enyby In that case, can you share a smali file/class that exhibits this problem? Smali shouldn't be generating these errors :)

**Comment by JesusFreke** [comment]
Oh, nevermind. I know what this is. This happens when you do something like `goto :somelabel`, but don't actually have `:somelabel` anywhere. Sorry, I confused myself based on the way you phrased the question. :)   Yes, in that case, smali should definitely generate a better error, with the name of the label and the file/location where the error happened.
