### ISSUE TITLE
Exception when examining the Nfc app on Sony D2403 running Android 5.1.1

### ISSUE THREAD

**Issue by NCrouther** [JesusFreke/smali#400]
My application examines the com.android.nfc application's dex file at runtime to examine some of its behavior to let our application work around inconsistencies in different phones' implementations of this application.  The following exception was logged to Crashlytics:

Caused by org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x3c53c
       at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:58)
       at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
       at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:141)
       at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
       at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)

**Comment by JesusFreke** [comment]
This typically means that the dex file is corrupt in some way. The only way that this can happen legitimately is if the dex file is over 2gb in size, which seems... unlikely.

**Comment by NCrouther** [comment]
I'll try to get a phone and see if I can extract the dex file that causes the problem.  It seems strange that a system app would be corrupt, but since it has only happened once, I suppose anything's possible.

**Comment by JesusFreke** [comment]
Sounds good! Feel free to reopen the issue if you get a dex file that's exhibiting this problem.
