### ISSUE TITLE
ClassNotFoundException org.jf.util.ExceptionWithContext

### ISSUE THREAD

**Issue by antoniolm23** [JesusFreke/smali#404]
Hi, 
I followed the procedure described into the BuildProcedure guide inside the wiki, I generated the .jar files for smali, backsmali and dexlib2. I included those jars inside my eclipse project (a simple Java application). Unfortunately when I run the main I get this error
Exception in thread "main" java.lang.NoClassDefFoundError: org/jf/util/ExceptionWithContext
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	...
Caused by: java.lang.ClassNotFoundException: org.jf.util.ExceptionWithContext
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 14 more
I also checked if the .dex file I wanted to parse exists and it does. The function I'm calling is the following: 
DexFile dexFile = DexFileFactory.loadDexFile(file, 18, false);
Thanks in advance
Antonio

**Comment by antoniolm23** [comment]
Sorry to bother, 
I just checked that the error was due to a missing jar, the one referring to the util, in fact when I included that jar into my eclipse project that issue was solved 
Antonio
