### ISSUE TITLE
Problem with deodexing file: Cannot locate boot class path file

### ISSUE THREAD

**Issue by dirkjanm** [JesusFreke/smali#411]
I'm trying to deodex a .odex file from an LG system image (android 6.0):
`java -jar baksmali-2.1.2.jar LGApplicationManager.odex -a 23 -x -d framework/ `

This gives the following error:
```
Error occurred while loading boot class path files. Aborting.
org.jf.util.ExceptionWithContext: Cannot locate boot class path file /system/framework/core-libart.jar
	at org.jf.dexlib2.analysis.ClassPath.loadClassPathEntry(ClassPath.java:277)
	at org.jf.dexlib2.analysis.ClassPath.fromClassPath(ClassPath.java:182)
	at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:67)
	at org.jf.baksmali.main.run(main.java:113)
	at org.jf.baksmali.main.main(main.java:322)
```
core-libart.jar is in the framework/ directory

I've also tried to include the boot.oat:
```
java -jar baksmali-2.1.2.jar LGApplicationManager.oat -a 23 -x -c framework/arm/boot.oat 

Error occurred while loading boot class path files. Aborting.
org.jf.util.ExceptionWithContext: Cannot locate boot class path file framework/arm/boot.oat
	at org.jf.dexlib2.analysis.ClassPath.loadClassPathEntry(ClassPath.java:277)
	at org.jf.dexlib2.analysis.ClassPath.fromClassPath(ClassPath.java:182)
	at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:67)
	at org.jf.baksmali.main.run(main.java:113)
	at org.jf.baksmali.main.main(main.java:322)
```
boot.oat exists here also:
```
find system/ -name boot.oat
system/framework/arm/boot.oat
system/framework/arm64/boot.oat
```

I've tried combining -d with -c and switching the arm for arm64, but all without luck, I keep getting the same error.
Any thoughts on what I'm doing wrong?

**Comment by JesusFreke** [comment]
Try:

java -jar baksmali-2.1.2.jar LGApplicationManager.oat -a 23 -x -c boot.oat -d framework/arm

**Comment by dirkjanm** [comment]
Ahhhh that works... I wonder why I didn't come up with this myself while looking at the examples. Maybe the error could be made a bit more specific so it includes the file it can't find and where it is looking for it given the command line options?

**Comment by JesusFreke** [comment]
A complete revamp of the command line interface is underway :)
