### ISSUE TITLE
boot.oat in Asus ZenFone 2 (ZE551ML) lollipop is v39

### ISSUE THREAD

**Issue by SocialLoginDev** [JesusFreke/smali#417]
Hello.
I want to decompile the FM radio application.
But when trying to run baksmali - crash:

$ java -jar baksmali.jar -d framework -x AsusFMRadio.odex
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedOatVersionException: Unsupported oat version: 39
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:147)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
	at org.jf.baksmali.main.main(main.java:292)

Thanks.

**Comment by JesusFreke** [comment]
Yep, that version is indeed unsupported :)

That was prior to some fixes/changes in art relating to field ordering which is needed for proper deodexing.

**Comment by cweiske** [comment]
A hint for others finding this issue when searching for the error message:

I was able to deodex a Android 5 odex file with the `oat2dex.jar` linked in https://www.naldotech.com/how-to-deodex-applications-on-android-5-0-lollipop/ (download: http://forum.xda-developers.com/attachment.php?attachmentid=3055129&d=1418113412)
