### ISSUE TITLE
Need support for deodex Android N

### ISSUE THREAD

**Issue by rvceboy** [JesusFreke/smali#418]
Hi,
Its been close to 6 months since Android N Release.
Still unable to deodex the Android N applications.

Any help would be appreciated.

thank you

**Comment by mfonville** [comment]
I have a small explicit request for this one: de-odexing HotwordEnrollment from the Nexus 6P NRD90M image fails :-/
any possible fix?

**Comment by mfonville** [comment]
Another two failing, this time from the Fugu NRD90M:
Overscan RemoteControlService

**Comment by JesusFreke** [comment]
I'm working on it :). I haven't looked at those specifically, but right now I'm tracking down an issue with how the vtable is calculated, which seems to be related to the new default methods.

**Comment by TheCrazyLex** [comment]
Awesome thanks! @JesusFreke

**Comment by JesusFreke** [comment]
N deodexing should be working in the latest v2.2_WIP. I'm hoping to have an initial beta release "real soon now"

**Comment by mfonville** [comment]
@JesusFreke thanks for your work!
Much appreciated; should we wait for the 'beta release' before even trying to de-odex, or would you think the current WIP is already stable enough to produce reliable APKs?

**Comment by JesusFreke** [comment]
There are no known issues with deodexing with the current WIP. I'm actually hoping to get the beta out today, but we'll see :)

**Comment by ale5000-git** [comment]
Very very good.
Thanks :)

**Comment by JesusFreke** [comment]
And v2.2b1 is out :). Give it a shot and let me know!

**Comment by rvceboy** [comment]
$ java -jar baksmali.jar deodex /home/ClockworkHomeGoogle.apk -b framework/x86/boot.oat

Exception in thread "main" com.beust.jcommander.ParameterException: java.lang.InstantiationException: org.jf.util.jcommander.ColonParameterSplitter
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1309)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1228)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:241)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:209)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:875)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:857)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:791)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at org.jf.baksmali.Main.main(Main.java:90)
Caused by: java.lang.InstantiationException: org.jf.util.jcommander.ColonParameterSplitter
	at java.lang.Class.newInstance(Class.java:427)
	at com.beust.jcommander.JCommander.convertToList(JCommander.java:1326)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1302)
	... 12 more
Caused by: java.lang.NoSuchMethodException: org.jf.util.jcommander.ColonParameterSplitter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 14 more

**Comment by rvceboy** [comment]
& when i build the jar myself & try to run the command to deodex
i get this response

no main manifest attribute, in baksmali.jar

**Comment by mfonville** [comment]
For me 2.2b1 works to de-compile Fugu `Overscan`, but it still fails on `RemoteControlService` :-/

**Comment by JesusFreke** [comment]
@rvceboy oops, proguard strikes again! As a workaround, you can try "java -jar baksmali.jar deodex /home/ClockworkHomeGoogle.apk -d framework/x86/". I'll get a new build up this evening.

**Comment by JesusFreke** [comment]
@mfonville thanks, I'll take a look

**Comment by JesusFreke** [comment]
@rvceboy Actually, I see the -d options triggers the same error. So the workaround is to copy all oat files from framework/<arch> to the same directory as the oat file you're deodexing, and don't pass any -b or -d options to baksmali. It will find the boot.oat file in the same directory automatically.

**Comment by JesusFreke** [comment]
@mfonville Are you getting an error when trying to deodex RemoteControlService? Or are you getting a failure on the device when you try to use it?

I just deodexed it with v2.2b1 and it seemed to deodex without any problems.

**Comment by mfonville** [comment]
@JesusFreke I had the problem during the de-odex phase, but I used @testwhat his wrapper, so that might have caused issues. I will try to do it using smali directly tomorrow.

**Comment by JesusFreke** [comment]
@rvceboy v2.2b2 should fix the ColonParameterSplitter error

**Comment by rvceboy** [comment]
No luck
$ java -jar baksmali.jar deodex /oat/x86/ClockworkHomeGoogle.odex -d framework/x86/

Exception in thread "main" com.beust.jcommander.ParameterException: java.lang.InstantiationException: com.beust.jcommander.converters.CommaParameterSplitter
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1309)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1228)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:241)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:209)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:875)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:857)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:791)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at org.jf.baksmali.Main.main(Main.java:90)
Caused by: java.lang.InstantiationException: com.beust.jcommander.converters.CommaParameterSplitter
	at java.lang.Class.newInstance(Class.java:427)
	at com.beust.jcommander.JCommander.convertToList(JCommander.java:1326)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1302)
	... 12 more
Caused by: java.lang.NoSuchMethodException: com.beust.jcommander.converters.CommaParameterSplitter.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 14 more

**Comment by rvceboy** [comment]
Actually i was trying to deodex android wear ClockworkHomeGoogle.apk
U can get the framework & apk from a emulator or google Download page
If its possible may be u can help me do that step by step.
That way u'll be able to resolve the issues faster

**Comment by JesusFreke** [comment]
Grrr, lol. 

Not really - because I likely wouldn't have run into that particular issue because I would have run it as

`baksmali deodex ClockworkHomeGoogle.apk -b framework/arm/boot.oat`

**Comment by rvceboy** [comment]
java -jar baksmali.jar deodex ClockworkHomeGoogle.apk -b framework/arm/boot.oat
Exception in thread "main" org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: Could not find entry classes.dex in ClockworkHomeGoogle.apk.
	at org.jf.dexlib2.DexFileFactory$DexEntryFinder.findEntry(DexFileFactory.java:382)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:87)
	at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:140)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:153)
	at org.jf.baksmali.Main.main(Main.java:102)

**Comment by JesusFreke** [comment]
Right, you want to deodex the odex file, not the apk :)

**Comment by rvceboy** [comment]
yes

**Comment by rvceboy** [comment]
there is a  oat/x86/ClockworkHomeGoogle.odex & ClockworkHomeGoogle.apk
if i'm not wrong odex contains the source ?

**Comment by JesusFreke** [comment]
Neither contains the source. The odex file does contain an optimized copy of the dex file though.

**Comment by rvceboy** [comment]
so is there no way to get the source then?

**Comment by JesusFreke** [comment]
Annnnd 2.2b3 is out. I'm pretty sure that squashed the remaining issues related to using proguard with jcommander.

**Comment by rvceboy** [comment]
Hi, thanks alot
It worked !!!

**Comment by rvceboy** [comment]
what is the smali command to get the actual source code?

**Comment by rvceboy** [comment]
Thanks alot..
Now i have the source code..

**Comment by mfonville** [comment]
@JesusFreke with directly calling smali/baksmali it does indeed work! Thanks!

**Comment by ale5000-git** [comment]
@JesusFreke: It works fine but I have a question, under the framework folder there is both arm and arm64 with oat files, why?
Do I have to keep 2 versions of the deodexed file (for example framework.jar)?
If yes where they must be placed?

**Comment by JesusFreke** [comment]
arm64 devices also support art, so there are 2 copies of most things for each arch. It doesn't really matter which you use for deodexing - the dex files(s) should be the same for both oat files.

**Comment by JohnPriv** [comment]
@JesusFreke 
Thanks for your works but i have one question...
some oat files related to jar files like "framework.jar" content more than one "classes.dex"
and when i run this command `baksmali deodex framework/arm64/boot-framework.oat` i get the out folder to smali it later by smali command to get dex file but the problem is there is only one classes.dex file and  i'm sure there are two or 3 classes files in that oat file.....so could you tell me what the problem? please

**Comment by JesusFreke** [comment]
Yes, you need to deodex each dex file in the oat file. You can use the "list dex" command to list all the dex files, and then you can specify each dex file as if the oat file was a directory.

    > baksmali list dex boot.oat
    /system/framework/framework.jar
    /system/framework/framework.jar:classes2.dex
    > baksmali deodex boot.oat # deodexes the first dex file by default
    > baksmali deodex boot.oat/classes2.dex  # You don't have to use the full entry name, just the last component will work.

**Comment by JohnPriv** [comment]
@JesusFreke 
WOOOOOOOOW....thank you man it works fine now

**Comment by agorski3** [comment]
@JesusFreke: I am trying to deodex all the oat files in the /system/framework/arm directory of a build of android n. These would be the files included in the boot classpath. Of course they decided to split up the boot.oat into the following many files:

boot.oat, boot-core-libart.oat, boot-conscrypt.oat, boot-okhttp.oat, boot-core-junit.oat, boot-bouncycastle.oat, boot-ext.oat, boot-framework.oat, boot-telephony-common.oat, boot-voip-common.oat, boot-ims-common.oat, boot-apache-xml.oat, boot-org.apache.http.legacy.boot.oat

So with these changes (to baksmali and android n) do we need to provide the complete boot classpath when deodexing each oat file and the directory containing the files, just the boot.oat file, nothing, or something inbetween? 

Oh and when specifying which dex file to extract from an oat file, is it still possible to give the full oat entry name with an -e option or do we need to list it like you have above with just the dex name after the oat file?

**Comment by JesusFreke** [comment]
Just the boot.oat. The other oat files are all listed in a "bootclasspath" section in the header of the oat files, so baksmali knows to look them up and load them.

-e is no longer supported

**Comment by agorski3** [comment]
Ah I see you removed the -e option in favor of finding the best match for the string appended with the directory separator to the file being used as input. for entries in containers. 

This seems a bit strange to me as you could have gotten the same effect by keeping the -e option and adding the best match procedure its processing without having to use code like this:

```
File file = new File(input);
while (file != null && !file.exists()) {
   file = file.getParentFile();
}
```

To me this seems like it could cause issues in unexpected ways.

**Comment by JesusFreke** [comment]
My original intention was to use that same syntax in the classpath/bootclasspath lists to allow specifying a specific entry, but I eventually scrapped that because you really only need to load the entire oat file when using it as a dependency, rather than a specific entry.  But I decided to keep the new syntax anyway.

Really the only problem case that I'm aware of is if there are multiple dex entries that collide. e.g. I don't think there's any reason you couldn't have an oat file with an entry named, e.g. "blah/blah.dex", and then another named "/blah/blah.dex". I don't know of anything that produces entries without the initial '/' though, so I don't think it should be an issue in practice. But I did add some quoting syntax to handle this case, just in case.  `blah.oat/"/blah/blah.dex"` and `blah.oat/"blah/blah.dex"`  (eww! I know :p)

I don't know of any other potential problems.

**Comment by agorski3** [comment]
Right and I could not think of anything specific either. My point was that the code just seemed like the kind of thing that could error unexpectedly because what you are essentially doing is guessing at what the file is and what the entry is from a given string. Versus the old method where they were both given separately. 

Yes I agree quotes on the command line as part of a longer string is very much eww visually :p. Overall, it seems like you went and replaced something that was more obvious and easier to understand (i.e. the -e option) with something a bit confusing and visually offensive in some cases. Moreover, if you wanted to differentiate between exact matching and partial matching you could have just added another option say -ex for exact or something. 

The old -e option with maybe another for exact matching just seems like a better design to me, but this is just all my opinion of course.

**Comment by JesusFreke** [comment]
N deodexing is working as of the 2.2 beta
