### ISSUE TITLE
AnalysisException when deodexing services.odex (Samsung S7)

### ISSUE THREAD

**Issue by moneytoo** [JesusFreke/smali#433]
I'm unable to use baksmali (both latest stable or compiled build from master) to to deodex services.odex (from my variant of Samsung Galaxy S7). Other files are fine to deodex. Deodexing services using latest version of oat2dex also works (but neither works 100% for all odex files on device...).

```
$ java -jar baksmali-2.1.3.jar system/framework/oat/arm64/services.odex -a 23 -x -c system/framework/arm64/boot.oat -d system/framework/arm64 -e /system/framework/services.jar
org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Lmf/org/apache/xerces/dom/CoreDocumentImpl; at index 156
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1836)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1026)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:210)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:141)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 14
method: Lmf/org/apache/xerces/dom/DOMNormalizer;->normalizeDocument(Lmf/org/apache/xerces/dom/CoreDocumentImpl;Lmf/org/apache/xerces/dom/DOMConfigurationImpl;)V
```

I can provide the files or point to the specific Samsung ROM (I didn't test other builds but I can try if needed).

**Comment by JesusFreke** [comment]
Sure, if you can point me to the ROM, I can take a look.

**Comment by moneytoo** [comment]
It's the current ROM (ETL variant) for SM-G930F which can be downloaded eg from http://updato.com/firmware-archive-select-model?r=ETL&v=&q=G930F (it's the full firmware image which you can just untar and mount/extract the system ext4 partition)

**Comment by JesusFreke** [comment]
I didnt try to deodex the entire rom, but deodexing services.odex works with v2.2b1. Give it a shot and let me know!

**Comment by moneytoo** [comment]
I tried deodexing the entire rom (apps/framework) including services.odex using v2.2b3 and didn't notice any issue. Thanks for a prompt fix!
