### ISSUE TITLE
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedOatVersionException: Unsupported oat version: 45

### ISSUE THREAD

**Issue by oneal23** [JesusFreke/smali#435]
java -jar baksmali-2.1.3.jar -a 23 -x MiuiCamera.odex -o out -d ./framework
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedOatVersionException: Unsupported oat version: 45
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:147)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:78)
	at org.jf.baksmali.main.main(main.java:292)

**Comment by JesusFreke** [comment]
See #269 and #392

**Comment by 241d2** [comment]
I got the same problem

**Comment by oneal23** [comment]
@241d2 See #392
