### ISSUE TITLE
ColonParameterSplitter error with latest baksmali-2.2b1.jar

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#442]
C:\arm>java -jar baksmali-2.2b1.jar x -b boot.oat BasicDreams.odex
Exception in thread "main" com.beust.jcommander.ParameterException: java.lang.InstantiationException: org.jf.util.jcommander.ColonParameterSplitter
        at com.beust.jcommander.JCommander.convertValue(JCommander.java:1309)
        at com.beust.jcommander.JCommander.convertValue(JCommander.java:1228)
        at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:241)
        at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:209)
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:875)
        at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:857)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:791)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at org.jf.baksmali.Main.main(Main.java:90)
Caused by: java.lang.InstantiationException: org.jf.util.jcommander.ColonParameterSplitter
        at java.lang.Class.newInstance(Class.java:427)
        at com.beust.jcommander.JCommander.convertToList(JCommander.java:1326)
        at com.beust.jcommander.JCommander.convertValue(JCommander.java:1302)
        ... 12 more
Caused by: java.lang.NoSuchMethodException: org.jf.util.jcommander.ColonParameterSplitter.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.newInstance(Class.java:412)
        ... 14 more

**Comment by JesusFreke** [comment]
Oops, that's what I get for not testing the proguarded binary :) I'll get a new build up this evening.

As a temporary workaround, if boot.oat is in the same directory as BasicDreams.odex, you can skip the "-b" option altogether. Or if it's in a different directory, specify the directory containing it with -d instead

So something like

    java -jar baksmali-2.2b1.jar x BasicDreams.odex

or

    java -jar baksmali-2.2b1.jar x -d framework/arm BasicDreams.odex

**Comment by JesusFreke** [comment]
Oh, the "-d" option triggers the ColonParameterSplitter error as well. So just put the boot.oat (and any other boot-*.oat files if on N) in the same directory as the file you're deodexing, and don't pass -d or -b

**Comment by JesusFreke** [comment]
v2.2b2 is out with a fix for this

**Comment by bursoft-git** [comment]
JF, thanks, v2.2b3 fixes this bug!
tell me, please, what is correct/prefer command line parameters for deodexind API 23 and above

for old v2.2_WIP i used something like this
java -jar baksmali-2.2_WIP.jar x -c "boot-apache-xml.oat:boot-bouncycastle.oat:boot-conscrypt.oat:boot-core-junit.oat:boot-core-libart.oat:boot-ext.oat:boot-framework.oat:boot-ims-common.oat:boot-okhttp.oat:boot-org.apache.http.legacy.boot.oat:boot-telephony-common.oat:boot-voip-common.oat:boot.oat:BasicDreams.odex" -d "_system\framework\arm" -d "_system\app\BasicDreams\oat\arm" "_system\app\BasicDreams\oat\arm\BasicDreams.odex:BasicDreams.apk"

can i simple use now
java -jar baksmali-2.2b3.jar x -b "_system\framework\arm\boot.oat" "_system\app\BasicDreams\oat\arm\BasicDreams.odex/system/app/BasicDreams/BasicDreams.apk" 

or prefer

java -jar baksmali-2.2b3.jar x -d "_system\framework\arm" "_system\app\BasicDreams\oat\arm\BasicDreams.odex/system/app/BasicDreams/BasicDreams.apk" 

?

**Comment by JesusFreke** [comment]
Either way should be fine. Personally, I would use -b in that case.
