### ISSUE TITLE
Could not resolve the field in class * with latest baksmali-2.2b3.jar

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#449]
When i deodex files from firmware API 18 with latest baksmali-2.2b3.jar , i got many errors 

```
java -jar baksmali-2.2b3.jar x -a 18 -d _system\framework "_system\framework\android.policy.odex"


org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Lcom/android/internal/policy/impl/EnableAccessibilityController$2; at offset 8
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1704)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1015)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:201)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:131)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:136)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:43)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:60)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.jf.dexlib2.analysis.AnalysisException: Could not resolve the field in class Lcom/android/internal/policy/impl/EnableAccessibilityController$1; at offset 28
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1704)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1015)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:201)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:131)
	at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:136)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:43)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:60)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:58)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
opcode: iput-object-quick
code address: 0
method: Lcom/android/internal/policy/impl/EnableAccessibilityController$1;-><init>(Lcom/android/internal/policy/impl/EnableAccessibilityController;)V
```

baksmali-2.1.3 deodex these files without errors

[framework_API18.zip](https://yadi.sk/d/EN-4-vvwwGY5x)

**Comment by JesusFreke** [comment]
Thanks, I'll take a look

**Comment by JesusFreke** [comment]
This should be fixed in 2.2b4

**Comment by ale5000-git** [comment]
I don't see 2.2b4 on github.

**Comment by JesusFreke** [comment]
Oops, I forgot to push the tags. It should be up now.

**Comment by bursoft-git** [comment]
JesusFreke, 2.2b4 solved this issue, thanks!
I have one question. My deodexing script delete *.odex files after proper deodexing.
This is not a problem when using baksmali-2.1.3 (maybe, it loads classpath entry from *.jar files?), but with 2.2b4 i got many errors after deleting *.odex files from bootclasspath dir

```
Error occurred while loading class path files. Aborting.
org.jf.dexlib2.analysis.ClassPathResolver$ResolveException: org.jf.dexlib2.analysis.ClassPathResolver$NotFoundException: Could not find classpath entry /system/framework/android.policy.odex
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:136)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:106)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:134)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:91)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:204)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:178)
	at org.jf.baksmali.Main.main(Main.java:102)
Caused by: org.jf.dexlib2.analysis.ClassPathResolver$NotFoundException: Could not find classpath entry /system/framework/android.policy.odex
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:207)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:121)
	... 7 more
```

so, now i need always keep all *.odex files during deodexing?
thanks!

**Comment by JesusFreke** [comment]
Filed as #464
