### ISSUE TITLE
[BUG] command line parsing

### ISSUE THREAD

**Issue by Lanchon** [JesusFreke/smali#452]
tested against 2.2b2
```
$ baksmali --help
Exception in thread "main" java.lang.NullPointerException
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1305)
	at com.beust.jcommander.JCommander.convertValue(JCommander.java:1228)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:241)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:209)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:722)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at org.jf.baksmali.Main.main(Main.java:90)
```

**Comment by agorski3** [comment]
The current version is 2.2b3 and it was changed because of errors in the command line parsing if I remember correctly. You may want to double check the error against the current version. I ran the command `java -jar baksmali-2.2b3.jar --help` without any issue just now.

**Comment by Lanchon** [comment]
thanks, you are right!
