### ISSUE TITLE
The last instruction in the method is truncated??

### ISSUE THREAD

**Issue by ibslkvic** [JesusFreke/smali#467]
While attempting to disassemble classes.dex from framework.jar with baksmali-2.2b4.jar received the following error below. 

$ java -Xms512m -Xmx1g -jar baksmali-2.2b4.jar d -a 22 classes.dex
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:178)
        at org.jf.baksmali.Main.main(Main.java:102)
Caused by: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:86)
        ... 2 more
Caused by: org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:75)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.findFieldsSetInStaticConstructor(ClassDefinition.java:72)
        at org.jf.baksmali.Adaptors.ClassDefinition.<init>(ClassDefinition.java:57)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:124)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by JesusFreke** [comment]
Can you link to the classes.dex? Also, are you sure you're using the correct api level?

**Comment by ibslkvic** [comment]
Device is Android 5.1.1 LG should be API 22 right? Here is a link to the classes.dex and the boot.oat it was pulled from.... Thanks for your help
https://drive.google.com/open?id=0B5GeJ2rXgxD-aE9PVzBKbGE2ckE

**Comment by JesusFreke** [comment]
Thanks. It's worth noting that baksmali doesn't support deodexing oat files from before Marshmallow.

The truncated last instruction thing is a bug though, and it's fixed in 8e1afdda32a3c6572e44ccba9150f18627bf834d. And I've improved the error message in a0ccd94bf9c653107629ea3d94dd6db9bf94c0d9

**Comment by peraltagroup** [comment]
Thanks for your help!
