### ISSUE TITLE
Apktool build fails on a very long smali file

### ISSUE THREAD

**Issue by gilhartman** [JesusFreke/smali#469]
1. Download Facebook work version 91.0.0.17.68 for Android 5.0+ from: https://apkpure.com/workplace-by-facebook/com.facebook.work/download?from=details%2Fversion&fid=c/APK/1958/027bc87efb31a718
2. Decode the apk with apktool
3. Open file smali_classes2/com/facebook/graphql/enums/GraphQLObjectType$ObjectType.smali and insert any valid 8 smali lines into the file
4. Build the modified folder with apktool
5. I get: Exception in thread "main" java.lang.IllegalStateException: Target is out of range at org.jf.dexlib2.builder.BuilderOffsetInstruction.getCodeOffset(BuilderOffsetInstruction.java:53)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:206)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:988)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:803)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:252)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:230)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:53)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:38)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:400)
	at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:346)
	at brut.androlib.Androlib.build(Androlib.java:288)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)

* I tried simulating this by creating a very long smali file in a less complex app, I did not get that error.

Attaching an example of the changed file
[GraphQLObjectType.zip](https://github.com/JesusFreke/smali/files/573838/GraphQLObjectType.zip)

**Comment by JesusFreke** [comment]
This is an issue with the if-eqz instructions later in the file. In particular, with the one that occurs just after the "TimelinePrompt" case at line 37866.

With the added instructions, the jump offset for the if-eqz is too large. One possible solution would be to replace the if-eqz with if-nez and goto/32 (the if-nez would jump forward, past the goto/32).

The error message that smali produces for this isn't actionable. I've improved the error message somewhat in 5e387e59311b0115ce769dea93c787076c5d7d82. I would prefer to actually give a specific file+line number for this, but the current structure of the code makes that difficult - similarly to, e.g. issue #399.

The error message now will be:

    Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lcom/facebook/graphql/enums/GraphQLObjectType$ObjectType;->a(Ljava/lang/String;)I
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:824)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:245)
        at org.jf.smali.Smali.assemble(Smali.java:130)
        at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
        at org.jf.smali.Main.main(Main.java:99)
    Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x8006
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1076)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:820)
        ... 5 more
    Caused by: org.jf.util.ExceptionWithContext: Invalid instruction offset: -32774. Offset must be in [-32768, 32767]
        at org.jf.dexlib2.builder.BuilderOffsetInstruction.getCodeOffset(BuilderOffsetInstruction.java:60)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:215)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1012)
        ... 6 more

This will at least give you the method name and the code offset. You can use the --offsets option when disassembling with baksmali to have it print out the code offsets, so you can identify the approximate location of the error.
