### ISSUE TITLE
Smalidea threw an uncaught NoReadAccessException

### ISSUE THREAD

**Issue by sealinglip** [JesusFreke/smali#476]
Error message:
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())

Details:
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 4386,4,Idea Thread Group] 1853157438
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2.2#AI-145.3360264 Studio, eap:false, os:Mac OS X 10.12.1, java-version:JetBrains s.r.o 1.8.0_112-release-b05,6,main] 1764364200
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1056)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:864)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:855)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:243)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:224)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:213)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:77)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:96)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:202)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:192)
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:39)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:65)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:89)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$5(CompoundPositionManager.java:87)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:69)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:86)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:153)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by daimajia** [comment]
+1

**Comment by JesusFreke** [comment]
Fixed by a15fc84ace690365ad55b66c98b27ffa7c35f1e6

**Comment by daimajia** [comment]
Thanks for your working on this useful and awesome project. @JesusFreke 

BTW. Is there any way to donate?

**Comment by JesusFreke** [comment]
I'm not able to accept donations. But thanks! I appreciate it :)

**Comment by ahMengli** [comment]
I came across the same error again, I am using Android Stdio 2.3.1 and Smalidea 0.0.5, both are the latest version, is there any solution to this problem?

**Comment by nanjingdaqi** [comment]
![image](https://user-images.githubusercontent.com/25942113/29300879-ff1d3458-81aa-11e7-85a6-35af350afbdf.png)
AS 2.3.3 and Smaliidea 0.0.5 came across the same issue again.

**Comment by runner56** [comment]
AS 2.3.3 and Smalidea v0.0.5 came across the same issue. Is there any solution to this problem? Thank you!
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 5,4,main] 52294496
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.4069837 Studio, eap:false, os:Windows 7 6.1, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 2049502642
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
