### ISSUE TITLE
Error "Incorrect field type "Ljava/lang/String;" for iget-quick" during deodexing

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#480]
When i deodex files from official SONY Xperia M4 Aqua firmware with baksmali-2.2b4.jar and latest commit https://github.com/JesusFreke/smali/commit/adb12356c30ee61b4585530b7c31e1e7e0eff349 , i got errors

```
c:\>java -jar baksmali-2.2b4.jar x -b boot.oat Hangouts.odex
org.jf.dexlib2.analysis.AnalysisException: Incorrect field type "Ljava/lang/String;" for iget-quick
        at org.jf.dexlib2.analysis.OdexedFieldInstructionMapper.getAndCheckDeodexedOpcode(OdexedFieldInstructionMapper.java:241)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAnalyzer.java:1759)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1015)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:201)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:131)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:326)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
opcode: iget-quick
code address: 135
method: Lihu;->b(Lcom/google/android/libraries/hangouts/video/internal/Stats;)V
```
and

```
c:\>java -jar baksmali-2.2b4.jar x -b boot.oat DeviceConfigTool.odex
org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Ljava/lang/Object; at index 22
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1858)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1017)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:201)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:131)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
opcode: invoke-virtual-quick
code address: 87
method: Lcom/google/android/gms/internal/jz;->d(Ljava/lang/Object;Ljava/lang/Object;)Z
```
Necessairy files here https://yadi.sk/d/Qb3Czvs737Pgkm
Thanks!

**Comment by JesusFreke** [comment]
This should be fixed by 1a83d5a2d052e7e5896741807e855e99668f755a
