### ISSUE TITLE
New baksmali does not support Dex version 036 deodexing?

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#484]
Hi, JesusFreke
When i deodex files from Lenovo P770 firmware with latest baksmali https://github.com/JesusFreke/smali/tree/1a83d5a2d052e7e5896741807e855e99668f755a , i got errors

```
java -jar baksmali-2.2.jar x -a 16 -d framework framework\am.odex

Error occurred while loading class path files. Aborting.
org.jf.dexlib2.util.DexUtil$UnsupportedFile: Dex version 036 is not supported
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:94)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:78)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:104)
	at org.jf.dexlib2.dexbacked.DexBackedOdexFile.<init>(DexBackedOdexFile.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedOdexFile.fromInputStream(DexBackedOdexFile.java:101)
	at org.jf.dexlib2.DexFileFactory.loadDexContainer(DexFileFactory.java:250)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:227)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:210)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:105)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:203)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)
```
With baksmali 2.1.3 error is
```
java -jar baksmali-2.1.3.jar -x -a 16 -d framework framework\am.odex

Error occurred while loading boot class path files. Aborting.
org.jf.util.ExceptionWithContext: Invalid magic value: 64 65 78 0a 30 33 36 00
	at org.jf.util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
	at org.jf.dexlib2.analysis.ClassPath.loadClassPathEntry(ClassPath.java:270)
	at org.jf.dexlib2.analysis.ClassPath.fromClassPath(ClassPath.java:182)
	at org.jf.baksmali.baksmali.disassembleDexFile(baksmali.java:67)
	at org.jf.baksmali.main.run(main.java:113)
	at org.jf.baksmali.main.main(main.java:322)
Caused by: org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 36 00
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.verifyMagicAndByteOrder(DexBackedDexFile.java:157)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:70)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
	at org.jf.dexlib2.dexbacked.DexBackedOdexFile.<init>(DexBackedOdexFile.java:54)
	at org.jf.dexlib2.dexbacked.DexBackedOdexFile.fromInputStream(DexBackedOdexFile.java:115)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:133)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:72)
	at org.jf.dexlib2.analysis.ClassPath.loadClassPathEntry(ClassPath.java:264)
	... 4 more
Error while reading boot class path entry "/system/framework/android.policy.odex"
```
With smali 1.4.2 files deodex correctly
`java -jar baksmali-1.4.2.jar -x -a 16 -d framework framework\am.odex`

Here is full framework folder https://yadi.sk/d/-0l52Vrq3BpseP
Thanks!

**Comment by Lanchon** [comment]
Dex version 036, hmmm...

https://source.android.com/devices/tech/dalvik/dex-format.html
> Note: Support for version 037 of the format was added in the Android 7.0 release. Prior to this release most versions of Android have used version 035 of the format. The only difference between versions 035 and 037 is the addition of default methods and the adjustment of the invoke instruction semantics to support this feature. **Due to a Dalvik bug present in older versions of Android, Dex version 036 has been skipped. Dex version 036 is not valid for any version of Android and never will be.**

**Comment by JesusFreke** [comment]
That is correct. You'll have to use an older version of baksmali. The 036 version was added for the partially implemented and eventually scrapped extensions to the dex format to allow > 64k method references (and fields, types, etc.). It was only available briefly, and was never really officially supported.

I'll have to dig a bit to find the last version of baksmali that supported that.

**Comment by Lanchon** [comment]
finally i know what 036 was about, thanks!

did you actually support it, or were you just not checking the version ID of the files?

**Comment by JesusFreke** [comment]
It was actually supported (in baksmali) at one point. And then I explicitly removed support since it was completely removed from dalvik, and never had any real usage, other than the small number of platform builds that used it - of which @bursoft-git seems to have found one :)

**Comment by JesusFreke** [comment]
I believe v1.3.3 was the last version that supported 036 odex/dexes.
