### ISSUE TITLE
Nullpointer exception in baksmali

### ISSUE THREAD

**Issue by philipphager** [JesusFreke/smali#486]
Hey,
the current baksmali version crashes for me while deconstructing a variety of files this exception.
I get it on every .apk I tried.

```

01-30 16:55:08.986 19977-25448/de.philipphager.disclosure.dev W/System.err: Error occurred while disassembling class Landroid.support.v7.widget.ActionMenuPresenter$ActionButtonSubmenu; - skipping class
01-30 16:55:08.986 19977-25448/de.philipphager.disclosure.dev W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'org.jf.dexlib2.util.SyntheticAccessorResolver$AccessedMember org.jf.dexlib2.util.SyntheticAccessorResolver.getAccessedMember(org.jf.dexlib2.iface.reference.MethodReference)' on a null object reference
01-30 16:55:08.986 19977-25448/de.philipphager.disclosure.dev W/System.err:     at org.jf.baksmali.Adaptors.MethodDefinition.addInstructionMethodItems(MethodDefinition.java:450)
01-30 16:55:08.986 19977-25448/de.philipphager.disclosure.dev W/System.err:     at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:373)
01-30 16:55:08.986 19977-25448/de.philipphager.disclosure.dev W/System.err:     at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
01-30 16:55:08.986 19977-25448/de.philipphager.disclosure.dev W/System.err:     at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
01-30 16:55:08.986 19977-25448/de.philipphager.disclosure.dev W/System.err:     at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
...
```

version: 2.2 b4

While calling baksmali like this:
```
Baksmali.disassembleDexFile(dexFile, outputDir, 4, new BaksmaliOptions());
```
Any clues on why that is?

**Comment by JesusFreke** [comment]
Sorry for the delay. This should be fixed by 961c21be988e842cb552e8e55f59b69656bffc6c
