### ISSUE TITLE
Error for input '.parameter': Invalid directive

### ISSUE THREAD

**Issue by d0ntchadon** [JesusFreke/smali#487]
Hi,

I am currently working on a old project created in 2013. From the search of the old issues here,
#241 

it seems like the problem is due to backwards compatibility issues and the solution was to assemble the samli file with smali v1.4.2 and disassemble it with the latest baksmali.

I manage to get the smali v1.4.2 jar file from:
http://repo.spring.io/repo/org/smali/smali/1.4.2/

However I couldnt run the jar file. it creates an error of:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2451)
	at java.lang.Class.getMethod0(Class.java:2694)
	at java.lang.Class.getMethod(Class.java:1622)
	at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.cli.ParseException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 6 more

Im sorry if this is not the right place to ask this. Please help me.

**Comment by JesusFreke** [comment]
It looks like that's probably the artifacts for maven repository. These are not "fat" jars with all the included dependencies, so you can't directly run them with java -jar.

You can download smali/baksmali 1.4.2 from the googlecode archive:

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/smali/smali-1.4.2.jar
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/smali/baksmali-1.4.2.jar
