### ISSUE TITLE
Error while I decompile services.odex running in 4.4.2

### ISSUE THREAD

**Issue by marckevinflores** [JesusFreke/smali#492]
but services.jar no problem for decompile

Error occurred while disassembling class Lcom.android.server.accessibility.AccessibilityManagerService; - skipping class
java.lang.RuntimeException: Invalid method index: 35
    at org.jf.dexlib2.analysis.InlineMethodResolver$InlineMethodResolver_version36.resolveExecuteInline(InlineMethodResolver.java:175)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeExecuteInline(MethodAnalyzer.java:1422)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:941)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:202)
    at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137)
    at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:387)
    at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:296)
    at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:198)
    at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:322)
    at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
    at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:220)
    at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
    at org.jf.baksmali.baksmali$1.call(baksmali.java:144)
    at org.jf.baksmali.baksmali$1.call(baksmali.java:142)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)

Error occurred while disassembling class Lcom.android.server.accessibility.TouchExplorer$InjectedPointerTracker; - skipping class
java.lang.RuntimeException: Invalid method index: 36
    at org.jf.dexlib2.analysis.InlineMethodResolver$InlineMethodResolver_version36.resolveExecuteInline

Do you have any tool to fix this Thanks for commenting

**Comment by JesusFreke** [comment]
Thank you :)

The most likely cause of this is that the OEM for your device modified the inline method table, adding some additional methods. The only way to resolve this is to download and compile the [deodexerant utility](https://github.com/JesusFreke/smali/tree/master/deodexerant) to dump the inline method table from your device, and then pass that to baksmali using the --inline-table option.

**Comment by marckevinflores** [comment]
but the guide of deodexerant not working, do you think what OS that will be working? sorry for bad english

**Comment by JesusFreke** [comment]
You'll have to be more specific, sorry :). Have you tried compiling it? Did it compile without errors? Were you able to run it on your device?

**Comment by marckevinflores** [comment]
not yet, i have a problem to adb push deodexerant /data/local 
its say failed to copy 'deodexerant.c' to '/data/local/deodexerant.c': Permission denied

**Comment by JesusFreke** [comment]
Nowhere in the instructions does it say to push deodexerant.c to the device.

**Comment by marckevinflores** [comment]
it is ok to push the deodexerant.c to my phone in manually? in data/local

**Comment by JesusFreke** [comment]
You can push it to the device if you want. It's not going to do you much good though. I would recommend compiling it first, using the instructions in the readme, and pushing the compiled binary to the device.

**Comment by marckevinflores** [comment]
that is the compiled binary? that is deodexerant.c?

**Comment by JesusFreke** [comment]
nope. that is a source file.

**Comment by marckevinflores** [comment]
how can i get the source files? by decompile of .odex?  sorry but i dont know but thanks you for helping me
