### ISSUE TITLE
Exception in thread error

### ISSUE THREAD

**Issue by tomi229** [JesusFreke/smali#493]
Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 64 65 78 0a 30 33 37 00
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.verifyMagicAndByteOrder(DexBackedDexFile.java:151)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:70)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:79)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:54)
	at org.jf.baksmali.main.main(main.java:247)

**Comment by strazzere** [comment]
Can you post the dex file? The magic (like the error) doesn't match what dexlib2 is expecting. That file has `dex\n037\00` where dexlib2 is hardcoded to look only at `dex\n035\00` or `dex\n036\00`.

As a simple hack you could allow or modify the file - though if you post a link to it, it may be easier.

**Comment by tomi229** [comment]
[http://www67.zippyshare.com/d/218fg4o8/111816/classes.dex](dex file)
Thanks for helping me.

**Comment by JesusFreke** [comment]
version 37 dex files are supported in the latest beta versions of baksmali

**Comment by tomi229** [comment]
Thanks. I updated to the latest version. This time I got a different error message:
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: -x
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at org.jf.baksmali.Main.main(Main.java:90)

**Comment by JesusFreke** [comment]
Yes, the command line synax and parameters have changed. See "baksmali help"

**Comment by tomi229** [comment]
I looked for solution in the help but did not find anything. Could you please specify how to solve the problem?

**Comment by JesusFreke** [comment]
take a look at the "deodex" command.

**Comment by tomi229** [comment]
Sorry I still don't know what is the problem. This is my first time doing this.

**Comment by JesusFreke** [comment]
There is no "-x" option with the new command line syntax. The equivalent functionality is the deodex command. See https://github.com/JesusFreke/smali/wiki/SmaliBaksmali2.2 for more info on the new command line syntax. "baksmali help deodex" should be helpful as well.

**Comment by tomi229** [comment]
Where to write the command?

**Comment by ale5000-git** [comment]
@tomi229: If you use a different tool to run baksmali, just updating it will not work.
You must run baksmali manually from the command line.
