### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by zhengoogle** [JesusFreke/smali#501]
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/beust/jco
mmander/JCommander : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:14
2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.jf.baksmali.Main.main(Main.java:78)

**Comment by zhengoogle** [comment]
i use a new version jdk1.8,but it has a new exception:
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expecte
d a command, got -o
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
        at com.beust.jcommander.JCommander.parse(JCommander.java:304)
        at com.beust.jcommander.JCommander.parse(JCommander.java:287)
        at org.jf.baksmali.Main.main(Main.java:90)

**Comment by JesusFreke** [comment]
The command line syntax for smali 2.2 has changed. See "baksmali help" and https://github.com/JesusFreke/smali/wiki/SmaliBaksmali2.2
