### ISSUE TITLE
Deodexing broken on M and N after O updates

### ISSUE THREAD

**Issue by superr** [JesusFreke/smali#503]
Hello,

Thank you for the update to allow deodexing Android O. Unfortunately the update seems to have broken everything below O. Here is an [example apk and framework oat files](https://www.androidfilehost.com/?fid=673368273298943302) from Android 7.0 Galaxy s7. Below is the output of several tries using slightly different commands. Thank you for your time :)

```
superr@studio:/smali_test$ java -Xmx5000m -jar baksmali.jar list dex Tag/oat/arm64/Tag.odex
/system/priv-app/Tag/Tag.apk


superr@studio:/smali_test$ java -Xmx5000m -jar baksmali.jar deodex -b boot.oat Tag/oat/arm64/Tag.odex/Tag.apk -o smali

Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1866302676
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:241)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalClassPathEntry(ClassPathResolver.java:179)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:191)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:85)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:135)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:203)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)



superr@studio:/smali_test$ java -Xmx5000m -jar baksmali.jar deodex -c boot.oat Tag/oat/arm64/Tag.odex/Tag.apk -o smali

Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1866302676
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:241)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalClassPathEntry(ClassPathResolver.java:179)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:191)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:105)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:203)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)



superr@studio:/smali_test$ java -Xmx5000m -jar baksmali.jar deodex -a 24 -b boot.oat Tag/oat/arm64/Tag.odex/Tag.apk -o smali

Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1866302676
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:241)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalClassPathEntry(ClassPathResolver.java:179)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:191)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:85)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:135)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:203)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)



superr@studio:/smali_test$ java -Xmx5000m -jar baksmali.jar deodex -a 24 -c boot.oat Tag/oat/arm64/Tag.odex/Tag.apk -o smali

Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1866302676
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:241)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalClassPathEntry(ClassPathResolver.java:179)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:191)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:105)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:203)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)
```

**Comment by JesusFreke** [comment]
Hmm, I did try it on some M and N nexus firmwares without any issues. I'll have to take a look, thanks!

**Comment by Furniel** [comment]
Looks like android 6-7.1 deodexing is really broken now. Tested Pixel C factory images(6.0.1 (MXC89L), 7.0.0 (NRD91N, Nov 2016), 7.1.1 (N4F26T, Mar 2017)) and getting two types of errors:
For android 6.0:
```
Exception in thread "main" org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x3694
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:58)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:81)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:100)
	at org.jf.dexlib2.dexbacked.OatFile$OatDexFile.<init>(OatFile.java:233)
	at org.jf.dexlib2.dexbacked.OatFile$DexEntry.getDexFile(OatFile.java:566)
	at org.jf.dexlib2.dexbacked.OatFile$1$1.apply(OatFile.java:194)
	at org.jf.dexlib2.dexbacked.OatFile$1$1.apply(OatFile.java:192)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at org.jf.util.AbstractForwardSequentialList$1.next(AbstractForwardSequentialList.java:91)
	at java.util.AbstractSequentialList.get(Unknown Source)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:129)
	at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:144)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:157)
	at org.jf.baksmali.Main.main(Main.java:102)
```
For 7.0 and for 7.1.1:
```
java.lang.ArrayIndexOutOfBoundsException: 1702134661
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:241)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:210)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:105)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:203)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)
```
