### ISSUE TITLE
Smalidea threw an uncaught NoReadAccessException (again)

### ISSUE THREAD

**Issue by dexhax** [JesusFreke/smali#505]
Possibly related: #476 

**Error Message**:
NoReadAccessException
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())

**Details**:
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 5,4,main] 1827080062
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.3764568 Studio, eap:false, os:Linux 3.13.0-112-generic, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 452862116
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Appreciate your work!

**Comment by qssq** [comment]
yes my

**Comment by qssq** [comment]
malidea threw an uncaught NoReadAccessException. Disable Plugin android studio 2.2.3

**Comment by ttcrack** [comment]
me too...
android studio 2.2.3

**Comment by sealinglip** [comment]
me too
Android studio 2.3.1

Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 7,4,Idea Thread Group] 1471730209
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.3871768 Studio, eap:false, os:Mac OS X 10.12.4, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 503504867
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Tom4t0** [comment]
I have also encountered the same problem

Android studio 2.2.1
Smalidea 0.0.5

```
NoReadAccessException
          Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
          Details: Current thread: Thread[ApplicationImpl pooled thread 142,4,Idea Thread Group] 1184882741
          ; dispatch thread: false; isDispatchThread(): false
          SystemEventQueueThread: Thread[AWT-EventQueue-0 2.2#AI-145.3330264 Studio, eap:false, os:Mac OS X 10.12.4, java-version:JetBrains s.r.o 1.8.0_112-release-b05,6,main] 300045751
```

**Comment by wyxy2005** [comment]
me too.
very bad!!!

**Comment by wyxy2005** [comment]
10:28	NoReadAccessException
				Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
				Details: Current thread: Thread[ApplicationImpl pooled thread 1,4,Idea Thread Group] 227159197
				; dispatch thread: false; isDispatchThread(): false
				SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.3934792 Studio, eap:false, os:Mac OS X 10.11.6, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 2063198652

**Comment by flufy3d** [comment]
me too Android Studio 2.3.3

**Comment by HackerGBD** [comment]
me too.. android studio 2.3.3   smalidea 0.0.5.
NoReadAccessException
		Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
		Details: Current thread: Thread[ApplicationImpl pooled thread 24,4,main] 2061826335
		; dispatch thread: false; isDispatchThread(): false
		SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.4069837 Studio, eap:false, os:Windows 7 6.1, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 364414053

**Comment by walunte** [comment]
same problem
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 4,4,main] 927385678
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.4069837 Studio, eap:false, os:Mac OS X 10.12.6, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 2030813043
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliMethod.getName(SmaliMethod.java:84)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:80)
	at org.jf.smalidea.debugging.SmaliPositionManager.getSourcePosition(SmaliPositionManager.java:96)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$getSourcePosition$0(CompoundPositionManager.java:95)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:77)
	at com.intellij.debugger.engine.CompoundPositionManager.getSourcePosition(CompoundPositionManager.java:94)
	at com.intellij.debugger.engine.ContextUtil.getSourcePosition(ContextUtil.java:65)
	at org.jf.smalidea.debugging.SmaliSteppingCommandProvider$1.action(SmaliSteppingCommandProvider.java:53)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by blastrock** [comment]
Same issue here AS 3.4.1, I can't print any register. Is there a workaround?
