### ISSUE TITLE
Nougat Deodexing Error On One PC...But Not Another

### ISSUE THREAD

**Issue by Ticklefish** [JesusFreke/smali#506]
Apologies if this is a stupid issue to make. I can't work out what's going on and Googling doesn't bring me any closer to an answer.
I have a Nougat rom that deodexes cleanly on my PC but not on somebody else's. Everything baksmalis and smalis without any trouble with the exception of boot-framework.oat. That comes up with this error:

"**Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/accessibilityservice/AccessibilityServiceInfo;-><init>(Landroid/content/pm/ResolveInfo;Landroid/content/Context;)V
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:824)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:245)
	at org.jf.smali.Smali.assemble(Smali.java:130)
	at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
	at org.jf.smali.Main.main(Main.java:99)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x52
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1076)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:820)
	... 5 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 68696
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:338)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1048)
	... 6 more**"

On my setup at work there's no error at all. I'm using Java 1.8.0_60 and they're on 1.8.0_121 but I can't see why that would cause an issue.

The process is the same (it's a batch file that does it), the files are the same, the versions of baksmali and smali are the same (2.2.0)...but the result is not. 

Any thoughts?

(Again, apologies if this is a really simple question)

**Comment by JesusFreke** [comment]
What is the result of: `baksmali list methods boot-framework.oat | wc -l`?

Or if you're on windows/don't have the wc utility:
baksmali list methods boot-framework.oat > methods.txt
and then how many lines are in methods.txt?

**Comment by Ticklefish** [comment]
Thanks for your reply.

There are 65529 methods in the boot-framework.oat. There are essentially two classes.dex files inside there.

I get that the "Unsigned short value out of range" is saying there's too many methods for one DEX file, which is understandable. It's just strange that this error shows on one PC and not another.

The batch file we're using first uses "java -Xmx1024m -jar baksmali.jar list dex boot-framework.oat > results.txt" to see how many files are inside the oat.
Each line of results.txt is fed into a process which uses "java -Xmx1024m -jar baksmali.jar deodex -c boot.oat -d framework/arm64 framework/arm64/boot-framework.oat" or "java -Xmx1024m -jar baksmali.jar deodex -o out2 framework/arm64/boot-framework.oat/classes2.dex" then the relevant smali to turn that file into a classes.dex (or a classes2.dex, classes3.dex, etc).

I know it's a batch file so normally I would assume that there's an issue with my code and not post here. But it's the fact that the exact same code and the exact same files work on one machine and not another that's puzzling me.
