### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by uplusplus** [JesusFreke/smali#516]
# java -jar /opt/baksmail.jar x -d $AR -d . -o pc com.paic.esale.activity-1.apk.classes3.zip 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 16673399
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.util.SyntheticAccessorResolver.<init>(SyntheticAccessorResolver.java:80)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:282)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)

# java -jar /opt/baksmail.jar x -d $AR -d . -o pc com.paic.esale.activity-1.apk.classes2.zip 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 15501367
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.util.SyntheticAccessorResolver.<init>(SyntheticAccessorResolver.java:80)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:282)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:177)
	at org.jf.baksmali.Main.main(Main.java:102)

**Comment by JesusFreke** [comment]
I believe this is a duplicate of #503, and was fixed by 9df7a67273f0b01fbe4ab49c4bd723d3de7da424. If you build a new baksmali from tip-of-tree, I think the problem should be resolved.
