### ISSUE TITLE
Trouble Deodexing bluetooth app

### ISSUE THREAD

**Issue by Kellwa** [JesusFreke/smali#517]
Please Help
trying to deodex /system/app/Bluetooth/oat/arm/Bluetooth.odex
when i try with baksmali-2.2.0.jar i get this error:
```
java -jar baksmali-2.2.0.jar -x -c boot.oat -d framework\arm Bluetooth.odex -o out

Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got -x
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
        at com.beust.jcommander.JCommander.parse(JCommander.java:304)
        at com.beust.jcommander.JCommander.parse(JCommander.java:287)
        at org.jf.baksmali.Main.main(Main.java:90)
```

When i try with baksmali-2.1.3.jar i get out folder with this errors :
```
java -jar baksmali-2.1.3.jar -x -c boot.oat -d framework\arm Bluetooth.odex -o out

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Landroid/view/View; at index 692
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1836)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1026)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:210)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:141)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
opcode: invoke-virtual-quick
code address: 10
method: Landroid/support/v4/app/SharedElementCallback;->onCaptureSharedElementSnapshot(Landroid/view/View;Landroid/graphics/Matrix;Landroid/graphics/RectF;)Landroid/os/Parcelable;



Error occurred while disassembling class Lcom.android.bluetooth.map.BluetoothMasService; - skipping class
org.jf.dexlib2.analysis.UnresolvedClassException: Interfaces for class Lcom/android/bluetooth/map/BluetoothMapAuthenticator; not fully resolved
        at org.jf.dexlib2.analysis.ClassProto.getDirectInterfaces(ClassProto.java:204)
        at org.jf.dexlib2.analysis.ClassProto$5.get(ClassProto.java:800)
        at org.jf.dexlib2.analysis.ClassProto$5.get(ClassProto.java:767)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
        at org.jf.dexlib2.analysis.ClassProto.getVtable(ClassProto.java:763)
        at org.jf.dexlib2.analysis.ClassProto.getMethodByVtableIndex(ClassProto.java:354)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1831)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1026)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:210)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:141)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:282)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class Ljava/lang/Object; at index 14
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1836)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1030)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:210)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:141)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:463)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
opcode: invoke-virtual-quick/range
code address: 798
method: Lcom/android/vcard/VCardEntry;->addProperty(Lcom/android/vcard/VCardProperty;)V
```
And if ignored all this and used smali i get this:
```
java -jar smali-2.1.3.jar -o classes.dex out

out\com\android\bluetooth\map\BluetoothMasService.smali[508,0] mismatched input '' expecting END_METHOD_DIRECTIVE
```
PS: My device is Htc desire 820 with Android 6.0.1 and i deodexed the hole rom with "TickleMyAndroid"
every thing is fine except bluetooth
and my device have both "arm" and "arm64" in the framework folder
please help me or guide me what to do
thanks in advance

**Comment by JesusFreke** [comment]
The CLI syntax in v2.2.0 has changed. See https://github.com/JesusFreke/smali/wiki/SmaliBaksmali2.2

**Comment by Kellwa** [comment]
tried with the new command and this is what i get:
```
java -jar baksmali.jar deodex Bluetooth.odex -b framework/arm/boot.oat


Error occurred while disassembling class Lcom.android.bluetooth.map.BluetoothMasService; - skipping class
org.jf.dexlib2.analysis.UnresolvedClassException: Interfaces for class Lcom/android/bluetooth/map/BluetoothMapAuthenticator; not fully resolved: Lcom/android/bluetooth/map/BluetoothMapAuthenticator;,Ljavax/obex/Authenticator;
        at org.jf.dexlib2.analysis.ClassProto.getDirectInterfaces(ClassProto.java:296)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:910)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:877)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
        at org.jf.dexlib2.analysis.ClassProto.getVtable(ClassProto.java:868)
        at org.jf.dexlib2.analysis.ClassProto.getMethodByVtableIndex(ClassProto.java:446)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1819)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1040)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:201)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:131)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:464)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:371)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
any idea whats going on ?

**Comment by JesusFreke** [comment]
The first step in troubleshooting an issue like that is to find where those classes are defined. Are they defined in a secondary dex file (e.g. classes2.dex) in the bluetooth app? Or in one of the framework files?

You can use the `baksmali list classes` functionality to list the classes in a dex file.

**Comment by Kellwa** [comment]
I did this `java -jar baksmali.jar list classes classes.dex` for the classes.dex from Bluetooth.apk and as i can see the class is in there
![untitled](https://cloud.githubusercontent.com/assets/16122152/26080068/99845bfa-39cd-11e7-9bb6-1bc23359153a.png)

**Comment by JesusFreke** [comment]
Per the error message, `Lcom/android/bluetooth/map/BluetoothMapAuthenticator;` and `Ljavax/obex/Authenticator;` are the classes it can't find

**Comment by Kellwa** [comment]
sorry my bad let me check again

**Comment by Kellwa** [comment]
the class `Lcom/android/bluetooth/map/BluetoothMapAuthenticator;` is in the bluetooth.apk classes
but the other one `Ljavax/obex/Authenticator;` is not
can you guide me where to look for it?

**Comment by JesusFreke** [comment]
I would look in any bluetooth-related framework files. is there an obex framework jar?

**Comment by Kellwa** [comment]
sorry for being slow to reply
i found the class in javax.obex.jar
what to do now?

**Comment by JesusFreke** [comment]
You can add the oat file for that jar to the locations that baksmali searches for classes, via the --classpath option

**Comment by Kellwa** [comment]
java -jar baksmali.jar deodex Bluetooth.odex -c javax.obex.jar

with this command i did not get any error
but could you give me step by step how to completely deodex Bluetooth.apk?
this is my first time to manually deodex an app :-)

**Comment by JesusFreke** [comment]
You want to reassemble the deodexed smali files with smali, and then add the dex file back into the apk file and resign.

**Comment by Kellwa** [comment]
Ok thank you so much
i will try
thanks man

**Comment by Kellwa** [comment]
the deodex progress went smoothly but the bluetooth didn't work on my mobile
i will try to deodex the hole rom manually
thanks for your help.

**Comment by Kellwa** [comment]
Every thing is working now
The problem was a missing lib file (or to be more accurate a broken symlink to the lib file libbluetooth_jni.so)
Solved it by coping that file from /system/lib to /system/app/Bluetooth/lib/arm
