### ISSUE TITLE
Error occurred while loading class path files.

### ISSUE THREAD

**Issue by argraur** [JesusFreke/smali#519]
```
$ java -jar baksmali-2.2.1.jar x SystemUI.odex


Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1852410276
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:78)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
        at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
        at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:163)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:105)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:207)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:181)
        at org.jf.baksmali.Main.main(Main.java:102)
```
```
$ ls
baksmali-2.2.1.jar                        boot.art                boot-ext.art          boot-legacy-test.oat                   boot-telephony-common.oat
boot-android.hidl.base-V1.0-java.art      boot-bouncycastle.art   boot-ext.oat          boot-legacy-test.vdex                  boot-telephony-common.vdex
boot-android.hidl.base-V1.0-java.oat      boot-bouncycastle.oat   boot-ext.vdex         boot.oat                               boot.vdex
boot-android.hidl.base-V1.0-java.vdex     boot-bouncycastle.vdex  boot-framework.art    boot-okhttp.art                        boot-voip-common.art
boot-android.hidl.manager-V1.0-java.art   boot-conscrypt.art      boot-framework.oat    boot-okhttp.oat                        boot-voip-common.oat
boot-android.hidl.manager-V1.0-java.oat   boot-conscrypt.oat      boot-framework.vdex   boot-okhttp.vdex                       boot-voip-common.vdex
boot-android.hidl.manager-V1.0-java.vdex  boot-conscrypt.vdex     boot-ims-common.art   boot-org.apache.http.legacy.boot.art   out
boot-apache-xml.art                       boot-core-libart.art    boot-ims-common.oat   boot-org.apache.http.legacy.boot.oat   SystemUI.odex
boot-apache-xml.oat                       boot-core-libart.oat    boot-ims-common.vdex  boot-org.apache.http.legacy.boot.vdex
boot-apache-xml.vdex                      boot-core-libart.vdex   boot-legacy-test.art  boot-telephony-common.art
```
--------------------------------------------------------------
Got this problem only when deodexing SystemUI.
Before deodexed services.jar and it was normal. :(

**Comment by argraur** [comment]
Just figured out, that SystemUI.vdex needs for deodexing too because that is Android O.
Issue closed.
