### ISSUE TITLE
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expecte d a command, got -o

### ISSUE THREAD

**Issue by Jasi2169** [JesusFreke/smali#524]
i use simple command to decompile classes.dex to folder

```
C:\Users\JASI\Desktop\Android>java -Xmx512M -jar Binaries\baksmali.jar -o Sourc
e/ classes.dex
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expecte
d a command, got -o
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
        at com.beust.jcommander.JCommander.parse(JCommander.java:304)
        at com.beust.jcommander.JCommander.parse(JCommander.java:287)
        at org.jf.baksmali.Main.main(Main.java:90)

C:\Users\JASI\Desktop\Android>
```

i updated baksmali n smali to latest version today and got this error,seems like you are using this new library for command parsing and causing the problem old baksmali works fine no error

and i see those old parameters are not available does it still allows output directory same as old one ?

**Comment by JesusFreke** [comment]
Yes, the command line syntax in baksmali 2.2 has changed. See "baksmali help" and https://github.com/JesusFreke/smali/wiki/SmaliBaksmali2.2.

In particular, you probably want the "disassemble" command (or "d" for short)
