### ISSUE TITLE
Has already been interned bug

### ISSUE THREAD

**Issue by Delphian2015** [JesusFreke/smali#529]
Hello. I am using apktool 2.2.3 . I decoded apk (for android 7.1) then trying to build and caught the error (I didn't change the file at all):
d:\apktool>apktool b base
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_assets folder into assets.dex...
base\smali_assets\java\com\d\b\a\a.smali[15,4] Class Lcom/d/b/a/a; has already b
een interned
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file
: java/com/d/b/a/a.smali
        at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:75)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:59)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
        at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:366)
        at brut.androlib.Androlib.build(Androlib.java:308)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:231)
        at brut.apktool.Main.main(Main.java:84)

**Comment by Delphian2015** [comment]
The error because of two copy of the folder in smali_assets the first one - smali_assets/java/com, the second smali_assets/com the folders have the same files, if I delete one of them I can build apk with warnings, but the apk doesn't work.

**Comment by sheep0704** [comment]
get
