### ISSUE TITLE
Baksmali throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by sebouh00** [JesusFreke/smali#533]
I'm getting the following exception when trying to run baksmali on Android O services.odex of Google Pixel.

```
Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1701056665
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:78)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:137)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:133)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:163)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:85)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:135)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:207)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:181)
	at org.jf.baksmali.Main.main(Main.java:102)
```

**Comment by JesusFreke** [comment]
What version of baksmali are you using?

Using the latest version (2.2.1) I was able to deodex services.odex via:

    adb pull /system/framework /tmp/framework
    baksmali x -d /tmp/framework/arm64 /tmp/framework/oat/arm64/services.odex

**Comment by sebouh00** [comment]
It's 2.2.1. You're command works though. I was trying:
`baksmali x -d ./framework/arm64 -b ./framework/arm64/boot.oat services.odex`
which worked on the samsung galaxy s7 and s8 service.odex.

**Comment by JesusFreke** [comment]
Hmm. I don't get the ArrayIndexOutOfBoundsException in that case either.

**Comment by sebouh00** [comment]
I'm trying for a pixel build OPP3.170518.006.

**Comment by Fatmajk** [comment]
I have the same error when trying to decode "Messages.odex" on Huawei P20 ROM. I'm using baksmali v2.2.2.

**Comment by Guts17** [comment]
I got this Exception on nexus5x OPM6.171019.030.E1 when trying to decode "wm.odex".
