### ISSUE TITLE
Assert failed when building smalidea

### ISSUE THREAD

**Issue by shizhx** [JesusFreke/smali#537]
```bash
cd smalidea
../gradew build
```
failed:
```
org.jf.smalidea.dexlib.SmalideaMethodTest > testPackedSwitch FAILED
    java.lang.RuntimeException
        Caused by: java.lang.AssertionError at SmalideaMethodTest.java:373

org.jf.smalidea.dexlib.SmalideaMethodTest > testSparseSwitch FAILED
    java.lang.RuntimeException
        Caused by: java.lang.AssertionError at SmalideaMethodTest.java:373

124 tests completed, 2 failed
:smalidea:test FAILED
```

stacktrace is too many, here is the key fragment:
```
Caused by: java.lang.AssertionError: expected:<6> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.jf.smalidea.dexlib.SmalideaMethodTest.checkSwitchElement(SmalideaMethodTest.java:373)
	at org.jf.smalidea.dexlib.SmalideaMethodTest.testPackedSwitch(SmalideaMethodTest.java:431)
```
```
Caused by: java.lang.AssertionError: expected:<6> but was:<3>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.jf.smalidea.dexlib.SmalideaMethodTest.checkSwitchElement(SmalideaMethodTest.java:373)
	at org.jf.smalidea.dexlib.SmalideaMethodTest.testSparseSwitch(SmalideaMethodTest.java:497)
```

**Comment by JesusFreke** [comment]
Might be some IDEA version incompatibility or something. The quick workaround is to add -x test to the gradle command to skip the tests
