### ISSUE TITLE
Plugin Error: NoReadAccessException

### ISSUE THREAD

**Issue by TheDauntless** [JesusFreke/smali#558]
Android Studio v2.3.2
Same thing on latest InteliJ version

The following message is triggered when I try to add "v0" in the watch window. During auto-complete of the v0 name, it correctly lists the type, but as soon as I "enter", I get the error:

<img width="551" alt="screen shot 2017-10-15 at 20 52 21" src="https://user-images.githubusercontent.com/1650034/31587937-d26995a8-b1ea-11e7-8d01-8d4fefacc31c.png">

<img width="549" alt="screen shot 2017-10-15 at 20 53 12" src="https://user-images.githubusercontent.com/1650034/31587939-e3a6fc7a-b1ea-11e7-982b-78746562f844.png">

    20:47	Plugin Error: Smalidea threw an uncaught NoReadAccessException. Disable Plugin

    20:47	NoReadAccessException
			Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
			Details: Current thread: Thread[ApplicationImpl pooled thread 17,4,Idea Thread 
    Group] 802196536
			; dispatch thread: false; isDispatchThread(): false
			SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.3934792 Studio, eap:false, os:Mac OS X 10.12.6, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 968030372

    20:47	Platform and Plugin Updates: The following components are ready to update: Google Play services, Google Repository, Android SDK Platform-Tools, Intel x86 Atom System Image, Intel x86 Atom_64 System Image, Android TV Intel x86 Atom System Image, Google APIs ARM 64 v8a System Image, Google APIs Intel x86 Atom System Image, Google APIs Intel x86 Atom_64 System Image

**Comment by TheDauntless** [comment]
Full stack trace:

```Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 17,4,Idea Thread Group] 802196536
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2.3#AI-162.3934792 Studio, eap:false, os:Mac OS X 10.12.6, java-version:JetBrains s.r.o 1.8.0_112-release-b06,6,main] 968030372
com.intellij.openapi.application.impl.ApplicationImpl$NoReadAccessException
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:945)
	at com.intellij.psi.impl.source.tree.CompositeElement.textToCharArray(CompositeElement.java:295)
	at com.intellij.psi.impl.source.tree.CompositeElement.getText(CompositeElement.java:265)
	at org.jf.smalidea.psi.impl.SmaliPrimitiveTypeElement.getType(SmaliPrimitiveTypeElement.java:51)
	at org.jf.smalidea.psi.impl.SmaliArrayTypeElement.getType(SmaliArrayTypeElement.java:61)
	at org.jf.smalidea.psi.impl.SmaliMethodParameter.getType(SmaliMethodParameter.java:89)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:85)
	at com.intellij.psi.util.MethodSignatureBackedByPsiMethod.create(MethodSignatureBackedByPsiMethod.java:68)
	at org.jf.smalidea.psi.impl.SmaliMethod.getSignature(SmaliMethod.java:193)
	at org.jf.smalidea.debugging.value.LazyStringReference.value(LazyStringReference.java:49)
	at com.intellij.debugger.ui.tree.render.ClassRenderer.calcLabel(ClassRenderer.java:116)
	at com.intellij.debugger.ui.tree.render.ArrayRenderer.calcLabel(ArrayRenderer.java:89)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.calcRepresentation(ValueDescriptorImpl.java:311)
	at com.intellij.debugger.ui.impl.watch.NodeDescriptorImpl.updateRepresentationNoNotify(NodeDescriptorImpl.java:84)
	at com.intellij.debugger.ui.impl.watch.NodeDescriptorImpl.updateRepresentation(NodeDescriptorImpl.java:76)
	at com.intellij.debugger.engine.JavaValue$1.contextAction(JavaValue.java:149)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.contextAction(SuspendContextCommandImpl.java:48)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:73)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:45)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:150)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:40)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:153)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:31)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```
