### ISSUE TITLE
Deodexing Android O 8.1 failed

### ISSUE THREAD

**Issue by kyvaith** [JesusFreke/smali#565]
Referring to #498 - I know this is crap - You just made android 8.0 to work, and now somebody need something which is not even released, but I need to get gapps form 8.1 image, to get Google Search with Assistant for x86 (Katnisss 3.0). This is image: https://dl.google.com/android/repository/sys-img/android-tv/x86-27_r01.zip

This is that I get:

```
C:\Users\kyvai\Desktop\system\framework\x86>java -jar C:\Users\kyvai\Downloads\baksmali-2.2.2.jar l d boot.oat
bootclasspath /system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-core-libart.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-conscrypt.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-okhttp.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-bouncycastle.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-apache-xml.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-legacy-test.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-ext.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-framework.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-telephony-common.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-voip-common.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-ims-common.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-org.apache.http.legacy.boot.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-android.hidl.base-V1.0-java.art:/system/framework/out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot-android.hidl.manager-V1.0-java.art compiler-filter speed concurrent-copying true debuggable false dex2oat-cmdline --runtime-arg -Xms64m --runtime-arg -Xmx64m --compiled-classes=frameworks/base/config/compiled-classes-phone --image-classes=frameworks/base/config/preloaded-classes --dirty-image-objects=frameworks/base/config/dirty-image-objects --dex-file=out/target/common/obj/JAVA_LIBRARIES/core-oj_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/core-libart_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/conscrypt_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/okhttp_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/bouncycastle_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/apache-xml_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/legacy-test_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/telephony-common_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/voip-common_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/ims-common_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/org.apache.http.legacy.boot_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/android.hidl.base-V1.0-java_intermediates/javalib.jar --dex-file=out/target/common/obj/JAVA_LIBRARIES/android.hidl.manager-V1.0-java_intermediates/javalib.jar --dex-location=/system/framework/core-oj.jar --dex-location=/system/framework/core-libart.jar --dex-location=/system/framework/conscrypt.jar --dex-location=/system/framework/okhttp.jar --dex-location=/system/framework/bouncycastle.jar --dex-location=/system/framework/apache-xml.jar --dex-location=/system/framework/legacy-test.jar --dex-location=/system/framework/ext.jar --dex-location=/system/framework/framework.jar --dex-location=/system/framework/telephony-common.jar --dex-location=/system/framework/voip-common.jar --dex-location=/system/framework/ims-common.jar --dex-location=/system/framework/org.apache.http.legacy.boot.jar --dex-location=/system/framework/android.hidl.base-V1.0-java.jar --dex-location=/system/framework/android.hidl.manager-V1.0-java.jar --oat-symbols=out/target/product/generic_x86/symbols/system/framework/x86/boot.oat --oat-file=out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot.oat --oat-location=/system/framework/x86/boot.oat --image=out/target/product/generic_x86/dex_bootjars/system/framework/x86/boot.art --base=0x70000000 --instruction-set=x86 --instruction-set-variant=x86 --instruction-set-features=default --android-root=out/target/product/generic_x86/system --runtime-arg -Xnorelocate --compile-pic --no-generate-debug-info --generate-build-id --multi-image --no-inline-from=core-oj.jar --generate-mini-debug-info dex2oat-host X86_64 native-debuggable false pic true

C:\Users\kyvai\Desktop\system\framework\x86>java -jar C:\Users\kyvai\Downloads\baksmali-2.2.2.jar x boot.oat/system/framework/core-oj.jar
Exception in thread "main" org.jf.dexlib2.DexFileFactory$DexFileNotFoundException: Could not find a dex entry in boot.oat matching system/framework/core-oj.jar
        at org.jf.dexlib2.DexFileFactory$DexEntryFinder.findEntry(DexFileFactory.java:428)
        at org.jf.dexlib2.DexFileFactory.loadDexEntry(DexFileFactory.java:211)
        at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:138)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:161)
        at org.jf.baksmali.Main.main(Main.java:102)
```

For reference, I've tried same thing with 8.0 image and works great.

Thanks for any help.

**Comment by lcweik** [comment]
you can use this repo to deodex android o's vdex file.

**Comment by lcweik** [comment]
https://github.com/lcweik/smali

**Comment by vaibhavp12345** [comment]
@lcweik, please extract this vdex file for me
https://www.dropbox.com/s/b3nzwg20hl5l491/SystemUIGoogle.vdex?dl=0

**Comment by Furniel** [comment]
@vaibhavp12345 
dex file:
[SystemUIGoogle.zip](https://github.com/JesusFreke/smali/files/1593127/SystemUIGoogle.zip)

**Comment by vaibhavp12345** [comment]
@Furniel thanks for the help, would you please extract this odex file for the last time, please....🤗
I would be thankful to you forever...

https://www.dropbox.com/s/kmzezz0kppfwst1/SystemUIGoogle.odex?dl=0

**Comment by vaibhavp12345** [comment]
@Furniel, so now can I decode the Dex that you provided me with smali 2.2.2???
