### ISSUE TITLE
Error deodex framework android 8

### ISSUE THREAD

**Issue by ale8530** [JesusFreke/smali#583]
I wanted to report some errors during the deodex of Android 8.0 with smali/baksmali 2.2.2

**boot-core-oj.oat**
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$InsertArguments.smali[413,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$GuardWithTest.smali[112,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$FilterArguments.smali[228,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$BindTo.smali[113,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$Construct.smali[238,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$DropArguments.smali[145,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$CollectArguments.smali[224,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$FilterReturnValue.smali[180,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$FoldArguments.smali[211,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$ExplicitCastArguments.smali[2224,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$Collector.smali[277,4] null
../../temp_for_deodex/system/framework/arm64/smali/java/lang/invoke/Transformers$CatchException.smali[167,4] null

**boot-framework.oat**
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/util/jar/StrictJarVerifier;->verifyBytes([B[B)[Ljava/security/cert/Certificate;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:825)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:268)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
	at org.jf.smali.Smali.assemble(Smali.java:130)
	at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
	at org.jf.smali.Main.main(Main.java:99)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0xa
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1098)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:821)
	... 5 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:348)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1058)
	... 6 more

Are the files necessary?

**Comment by vagyula1** [comment]
i got the same issue on the framework.jar (Android 8.0 based MIUI with baksmali 2.2.2)

Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/util/jar/StrictJarVerifier;->verifyBytes([B[B)[Ljava/security/cert/Certificate;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:825)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:268)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
	at org.jf.smali.Smali.assemble(Smali.java:130)
	at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
	at org.jf.smali.Main.main(Main.java:99)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x7
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1098)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:821)
	... 5 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65537
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:348)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1058)
	... 6 more

**Comment by ale8530** [comment]
me too MIUI android 8 this error causes bootloop

**Comment by ale8530** [comment]
same error core-j https://github.com/JesusFreke/smali/issues/568

**Comment by ale8530** [comment]
Hi @JesusFreke , is your kind answer possible? :)
