### ISSUE TITLE
Baksmali occasionally throws NullPointerException

### ISSUE THREAD

**Issue by BBIGBOSS** [JesusFreke/smali#609]
For the same command like:

java-8-openjdk-amd64/bin/java -Xms2048m -Xmx2048m -jar baksmali-2.2.2.jar deodex -o framework/baksmali framework/arm/boot.oat/system/framework/bouncycastle.jar

When I executed it many times, it could occasionally throw java.lang.NullPointerException on different stage like:

Error occurred while disassembling class Lcom.android.org.bouncycastle.asn1.DEROctetString; - skipping class
java.lang.NullPointerException
	at org.jf.baksmali.Adaptors.MethodDefinition$LabelCache.<init>(MethodDefinition.java:611)
	at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:77)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:280)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

or

Error occurred while disassembling class Lcom.android.org.bouncycastle.asn1.DERSequence; - skipping class
java.lang.NullPointerException
	at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:391)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

or

Error occurred while disassembling class Lcom.android.org.bouncycastle.asn1.ASN1String; - skipping class
java.lang.NullPointerException
	at org.jf.baksmali.Adaptors.ClassDefinition.writeClass(ClassDefinition.java:120)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:104)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Is there any code problems related to multithread ?

**Comment by JesusFreke** [comment]
Are you using a modified version of baksmali? Those line numbers do not match up with the source lines from the official 2.2.2 release.

e.g. this is [line 120](https://github.com/JesusFreke/smali/blob/master/baksmali/src/main/java/org/jf/baksmali/Adaptors/ClassDefinition.java#L120) in ClassDefinition. That's not even a valid source line.

Similarly, line [611 in MethodDefinition](https://github.com/JesusFreke/smali/blob/master/baksmali/src/main/java/org/jf/baksmali/Adaptors/MethodDefinition.java#L611) is not a valid source line.

And line [391 in MethodDefinition](https://github.com/JesusFreke/smali/blob/master/baksmali/src/main/java/org/jf/baksmali/Adaptors/MethodDefinition.java#L391) - it's at least a valid source line, but it's impossible for an NPE to be thrown there.

**Comment by BBIGBOSS** [comment]
md5 is 41877a502f6dc27066f071560e5cfbaa
downloaded from https://bitbucket.org/JesusFreke/smali/downloads/

**Comment by JesusFreke** [comment]
Hmm, yeah that looks right. I have no clue what's going on then. I guess I can try disassembling the jar and take a look at the line associations in the bytecode.

**Comment by JesusFreke** [comment]
Yeah, I suspect this is an issue with that specific openjdk version. I did a bit of searching saw at least one other reported issue where someone saw a strange NPE that was occurring on a return statement that shouldn't be able to cause an NPE, with that specific openjdk version.
