### ISSUE TITLE
[smalidea] plugin cause re-indexing to occur at non-stustainable frequency

### ISSUE THREAD

**Issue by elijahbal** [JesusFreke/smali#612]
#610  

As said in the title, the plugin cause too frequent reindexation of the folder's content, which causes instability and slowness when doing a step-by-step debugging session.

As a symptom, I encountered a crash in the so mentioned debugging session.

I think you can rule out os/linux/platform specific problem because I encountered in different environments.

Here is a backtrace I encountered.

```
Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:756)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:705)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:688)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:342)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:319)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:308)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
	at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:297)
	at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:287)
	at com.intellij.psi.stubs.AbstractStubIndex.get(AbstractStubIndex.java:39)
	at org.jf.smalidea.debugging.SmaliPositionManager$4.run(SmaliPositionManager.java:144)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:912)
	at org.jf.smalidea.debugging.SmaliPositionManager.locationsOfLine(SmaliPositionManager.java:138)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$locationsOfLine$4(CompoundPositionManager.java:149)
	at com.intellij.debugger.engine.CompoundPositionManager.lambda$iterate$0(CompoundPositionManager.java:91)
	at com.intellij.debugger.impl.DebuggerUtilsImpl.suppressExceptions(DebuggerUtilsImpl.java:224)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:91)
	at com.intellij.debugger.engine.CompoundPositionManager.iterate(CompoundPositionManager.java:76)
	at com.intellij.debugger.engine.CompoundPositionManager.locationsOfLine(CompoundPositionManager.java:149)
	at com.intellij.debugger.ui.breakpoints.LineBreakpoint.createRequestForPreparedClass(LineBreakpoint.java:125)
	at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.processClassPrepare(BreakpointWithHighlighter.java:265)
	at com.intellij.debugger.ui.breakpoints.Breakpoint.lambda$createOrWaitPrepare$2(Breakpoint.java:223)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.intellij.debugger.ui.breakpoints.Breakpoint.createOrWaitPrepare(Breakpoint.java:223)
	at com.intellij.debugger.ui.breakpoints.BreakpointWithHighlighter.createRequest(BreakpointWithHighlighter.java:249)
	at com.intellij.debugger.engine.JavaBreakpointHandler$1.action(JavaBreakpointHandler.java:56)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:47)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:147)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:43)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:155)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:32)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:61)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by elijahbal** [comment]
I noticed that this occurs if you mark the smali/ folder as source root.

Not doing that and it works fine.
