### ISSUE TITLE
Android P errors

### ISSUE THREAD

**Issue by Furniel** [JesusFreke/smali#621]
List dex error:
Command:
`java -jar baksmali.jar l dex arm\boot-framework.oat`
Expected output:
/system/framework/framework.jar
Got:
[boot-framework.oat.txt](https://github.com/JesusFreke/smali/files/2101486/boot-framework.oat.txt)
And program throws secound error(not related to additional info in dex list):
```
Exception in thread "main" org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset  0x37b60c
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:58)
        at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:594)
        at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:576)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at org.jf.baksmali.ListDexCommand.run(ListDexCommand.java:98)
        at org.jf.baksmali.ListCommand.run(ListCommand.java:83)
        at org.jf.baksmali.Main.main(Main.java:102)
```
Same error with x64 version of boot-framework.oat, but dex list doesn't contain additional info in this case:
```
Exception in thread "main" org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x393c9e
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:58)
        at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:594)
        at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:576)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at org.jf.baksmali.ListDexCommand.run(ListDexCommand.java:98)
        at org.jf.baksmali.ListCommand.run(ListCommand.java:83)
        at org.jf.baksmali.Main.main(Main.java:102)
```

And deodex error:

Command:
`java -jar baksmali.jar x -c arm64\boot.oat -d arm64 arm64\boot-android.hidl.base-V1.0-java.oat/system/framework/android.hidl.base-V1.0-java.jar -o out`
Error:
```
Error occurred while loading class path files. Aborting.
java.lang.IllegalArgumentException: bad utf-8 byte a7 at offset 00371f06
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:259)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:611)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.java:261)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getType(DexBackedDexFile.java:276)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:98)
        at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:49)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadEntry(ClassPathResolver.java:241)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:210)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:120)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:105)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:207)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:181)
        at org.jf.baksmali.Main.main(Main.java:102)
```

Framework files(taimen-ppp3.180510.008-factory-4ec49e55):
https://mega.nz/#!QgdEWKjA!L0ThSfJ4guplTLb9QXIIB3yWAAG-gLjXh7DVsLyJmPk

**Comment by ale5000-git** [comment]
The latest release doesn't yet include the neededx fix for Android P, you have to compile it yourself or wait 2.2.5

**Comment by Furniel** [comment]
@ale5000-git 
I didn't used release build. I compiled build with all latest commits and used it. This errors actual for current master branch state(https://github.com/JesusFreke/smali/commit/2fcdad20784ba3967733c2a91368c0c4d10d34d2).

**Comment by Nanolx** [comment]
I can reproduce the UTF-8 issue with baksmali 2.2.5 on-device with Pie ROMs.

I jused `dx --dex --min-sdk-version=26 baksmali-2.2.5 to make it executable on-device`.

command used to run baksmali:

```
	for jar in /system/framework/*.jar ; do
		BOOTCLASSES=${BOOTCLASSES}:${jar}
	done

		LD_LIBRARY_PATH=/system/lib:/system/vendor/lib:/vendor/lib \
			/system/bin/dalvikvm \
			-Xbootclasspath:${BOOTCLASSES} \
			-classpath "${BAKSMALI}" \
			org.jf.baksmali.Main \
			x "${BASEDIR}/services.odex" \
			-b "/system/framework/${ARCH}/boot.oat" \
			-d "/system/framework/${ARCH}" \
			-o "${BASEDIR}/services.jar-deodex" || \
				error " !! failed to deodex services.jar"
```

see [CommonPatcher](https://gitlab.com/Nanolx/NanoDroid/blob/master/patcher/CommonPatcher) for the full code (utilites used are in ../dexpatcher).

log:

```
Error occurred while loading class path files. Aborting.
java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 00002291
	at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
	at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:210)
	at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:611)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.java:261)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getType(DexBackedDexFile.java:276)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:98)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:49)
	at org.jf.dexlib2.analysis.PathEntryLoader.loadEntry(PathEntryLoader.java:62)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:203)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:113)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:98)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:209)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
	at org.jf.baksmali.Main.main(Main.java:102)
```

I uploaded the framework files, here: https://www.nanolx.org/apk/framework-pie.tar.xz

**Comment by ale8530** [comment]
Confirm

**Comment by Theliel** [comment]
Same here with 2.2.6

**Comment by zbyzhlsp** [comment]
same with 2.2.7

**Comment by foundkey** [comment]
same with 2.2.7 too.
for Android 9 (SDK 28): Mi MIX 2S, PKQ1.180729.001 image.
```
Error occurred while loading class path files. Aborting.
java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 00002580
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:210)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:611)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.java:261)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getType(DexBackedDexFile.java:276)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:98)
        at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:49)
        at org.jf.dexlib2.analysis.PathEntryLoader.loadEntry(PathEntryLoader.java:62)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:203)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:113)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:98)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:209)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
        at org.jf.baksmali.Main.main(Main.java:102)
```

**Comment by lapwat** [comment]
baksmali 2.2.5-dev
Android P, Xiaomi Redmi K20 Pro

```sh
baksmali x -c arm/boot.oat -d arm/ NQNfcNci.odex -o NQNfcNci/
```

```
Error occurred while loading class path files. Aborting.
java.lang.IllegalArgumentException: bad utf-8 byte 03 at offset 0000839c
	at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
	at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:238)
	at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:611)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.java:261)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getType(DexBackedDexFile.java:276)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:98)
	at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:49)
	at org.jf.dexlib2.analysis.PathEntryLoader.loadEntry(PathEntryLoader.java:62)
	at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:203)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:113)
	at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:98)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
	at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:209)
	at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
	at org.jf.baksmali.Main.main(Main.java:102)

```

Thank you for your work

**Comment by ale5000-git** [comment]
Have you tried version 2.3?
