### ISSUE TITLE
Unsigned short value out of range: 65537

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#629]
Hello JF!

C:\BatchApkTool\_system\framework\arm64>java -jar baksmali-2.2.4.jar l d boot-framework.oat
/system/framework/framework.jar
/system/framework/framework.jar:classes2.dex
/system/framework/framework.jar:classes3.dex

C:\BatchApkTool\_system\framework\arm64>java -jar baksmali-2.2.4.jar x -a 26 -b boot.oat boot-framework.oat/system/framework/framework.jar:classes2.dex

C:\BatchApkTool\_system\framework\arm64>java -jar smali-2.2.4.jar a -a 26 out
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/util/jar/StrictJarVerifier;->verifyBytes([B[B)[Ljava/security/cert/Certificate;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:886)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:313)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:269)
        at org.jf.smali.Smali.assemble(Smali.java:131)
        at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
        at org.jf.smali.Main.main(Main.java:99)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x7
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1159)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:882)
        ... 5 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65537
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1119)
        ... 6 more

Here is arm64 folder:
https://yadi.sk/d/3Bo4OBDq3Yfhp4

**Comment by bursoft-git** [comment]
smali 2.3 is still have this bug(
