### ISSUE TITLE
Encountered small uint that is out of range at offset 0x37b60c

### ISSUE THREAD

**Issue by bursoft-git** [JesusFreke/smali#633]
Hi JF!
When i try to get list of .dex files from .oat, i get error

```
java -jar baksmali-2.2.4.jar l d boot-framework.oat

/system/framework/framework.jar
    ,   /system/framework/framework.jar!classes2.dex????? ,? ? ?S ,9 ?D     ,   /system/framework/framework.jar!classes3.dexp?m???1 ? ? (T L ......

Exception in thread "main" org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x37b60c
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:58)
	at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:585)
	at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:576)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at org.jf.baksmali.ListDexCommand.run(ListDexCommand.java:98)
	at org.jf.baksmali.ListCommand.run(ListCommand.java:83)
	at org.jf.baksmali.Main.main(Main.java:102)
```

I use latest commit https://github.com/JesusFreke/smali/commit/2f29256bdf16303d459888083465946c8d1f6c47

Here is this file
[boot-framework.zip](https://github.com/JesusFreke/smali/files/2180542/boot-framework.zip)

Thanks!

**Comment by bursoft-git** [comment]
baksmali-2.3 works fine with this file! thanks!
