### ISSUE TITLE
Error occurred while loading class path files. smali2.2.5

### ISSUE THREAD

**Issue by L-Trump** [JesusFreke/smali#645]
->
java -jar baksmali.jar x framework/oat/arm64/services.odex -d framework/arm64 -d framework/ -o services-new

Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1786019759
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:147)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:143)
        at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
        at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
        at org.jf.dexlib2.analysis.PathEntryLoader.loadEntry(PathEntryLoader.java:62)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalClassPathEntry(ClassPathResolver.java:172)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:184)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:113)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:98)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:209)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
        at org.jf.baksmali.Main.main(Main.java:102)

Then->
E:\GumengToolbox\tool>java -jar baksmali.jar boot.oat
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got boot.oat
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
        at com.beust.jcommander.JCommander.parse(JCommander.java:304)
        at com.beust.jcommander.JCommander.parse(JCommander.java:287)
        at org.jf.baksmali.Main.main(Main.java:90)

The version of smali/baksmali is 2.2.5
Android version is Pie
Running Environment: JAVA jre, Windows 7
Who could tell me how to deal with the problem?Thanks

**Comment by JesusFreke** [comment]
Yeah, it looks like there were a couple of relevant changes to the oat format in P

I see

https://android.googlesource.com/platform/art/+/0f3c7003e08a42a4ed8c9f8dfffb1bee1118de59
and
https://android.googlesource.com/platform/art/+/ea341d2830298b666d7c6faf369d2fc3fe94fef8

**Comment by amlloc** [comment]
> Yeah, it looks like there were a couple of relevant changes to the oat format in P
> 
> I see
> 
> https://android.googlesource.com/platform/art/+/0f3c7003e08a42a4ed8c9f8dfffb1bee1118de59
> and
> https://android.googlesource.com/platform/art/+/ea341d2830298b666d7c6faf369d2fc3fe94fef8

Hi, I Meet the same problem ， Is there a solution for this issue?
thanks！
