### ISSUE TITLE
ArrayIndexOutOfBounds Error trying to extract Android Pie odex file

### ISSUE THREAD

**Issue by Zackptg5** [JesusFreke/smali#663]
```
java -Xmx1024m -jar baksma
li-2.2.5.jar x daxService.odex -d framework/arm64


Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 1650428069
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:147)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:143)
        at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
        at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:48)
        at org.jf.dexlib2.analysis.PathEntryLoader.loadEntry(PathEntryLoader.java:62)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:203)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:113)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:98)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:209)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
        at org.jf.baksmali.Main.main(Main.java:102)
```

I tried this with multiple odex files from motorola one power pie firmware and same error

**Comment by Zackptg5** [comment]
Not sure if this'll help but maybe this cdex stuff has something to do with it? https://github.com/anestisb/android-prepare-vendor/issues/130
