### ISSUE TITLE
48d13b297fa3f1dbf38054bd8f9f4e294f09273f makes baksmali fail when run on-device

### ISSUE THREAD

**Issue by AuroraWright** [JesusFreke/smali#676]
Commit 48d13b297fa3f1dbf38054bd8f9f4e294f09273f makes baksmali (converted to dex with dx, and run using dalvikvm) fail to disassemble a .dex on my Pixel 2 running Pie.
Log is as follows:
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
	at org.jf.baksmali.Main.main(Main.java:102)
Caused by: java.util.concurrent.ExecutionException: java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:86)
	... 2 more
Caused by: java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
	at org.jf.baksmali.Adaptors.Format.InstructionMethodItem.writeTo(InstructionMethodItem.java:132)
	at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:240)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(ClassDefinition.java:281)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:111)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassCastException: Bootstrap method returned null
	... 12 more
```

**Comment by Nightmare-MYS** [comment]
it same with my problem,have you still hava this problem
