### ISSUE TITLE
baksmali-2.2.6.jar: 'java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 002e4492'

### ISSUE THREAD

**Issue by sputnick-dev** [JesusFreke/smali#688]
Hi, 

trying to deodex LineageOS 16.0 alpha from Ubuntu 18.04.1 LTS, what I have done : 

    $ adb pull /system/framework framework
    $ cp framework/services.jar services.jar-backup
    $ wget https://bitbucket.org/JesusFreke/smali/downloads/baksmali-2.2.6.jar
    $ wget https://bitbucket.org/JesusFreke/smali/downloads/smali-2.2.6.jar
    $ java -jar baksmali-2.2.6.jar x framework/oat/arm64/services.odex -d framework/arm64 -d framework/ -o services-new

    Error occurred while loading class path files. Aborting.
    java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 002e4492
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:210)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:611)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.java:261)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getType(DexBackedDexFile.java:276)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:98)
        at org.jf.dexlib2.analysis.DexClassProvider.<init>(DexClassProvider.java:49)
        at org.jf.dexlib2.analysis.PathEntryLoader.loadEntry(PathEntryLoader.java:62)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:203)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:113)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:98)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:129)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:86)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:209)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
        at org.jf.baksmali.Main.main(Main.java:102)

Any clue ?

**Comment by heller390** [comment]
Boot class paths have to be passed manually . I am trying to use this command -b framework/[arch]/boot.oat . But its not getting accepted . Ideas are welcome.

**Comment by maciozo** [comment]
Also running into this issue.

**Comment by chenjiancheng** [comment]
me too

**Comment by jpstotz** [comment]
I am using dexlib2-2.3.4 and still getting this error:

```
java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 0005bcc4
	at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284) ~[dexlib2-2.3.4.jar:na]
	at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:210) ~[dexlib2-2.3.4.jar:na]
	at org.jf.dexlib2.dexbacked.DexReader.readString(DexReader.java:611) ~[dexlib2-2.3.4.jar:na]
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:269) ~[dexlib2-2.3.4.jar:na]
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:262) ~[dexlib2-2.3.4.jar:na]
```

At that time I was processing `assets/audience_network.dex` of the app `com.screenrecorder.recorder.audio.videoeditor` 1.0.4. 

The APK should be [this one](https://apkpure.com/de/screen-recorder-with-facecam-screenshot-capture/com.screenrecorder.recorder.audio.videoeditor).

**Comment by jackwpa** [comment]
That file presents lots of file format inconsistencies. Also, it does not match any of the published audience_network binaries (available on [Maven](https://search.maven.org/artifact/com.facebook.android/audience-network-sdk/5.6.1/aar)). It must be either corrupt, or has been modified and therefore must be restored before loading (obfuscation).
