### ISSUE TITLE
Smalidea watchers "Internal error"

### ISSUE THREAD

**Issue by kevanlanister735** [JesusFreke/smali#691]
Hello,

I am using IntelliJ IDEA 2019.1 and the smalidea plugin 0.05 to debug an application. It seems like the step debugging is working fine, but no matter which functions I am in, the v0,v1 and p0,p1 etc locals and parameters are showing as "Internal error" when I add them to watchers. 

I am using java8_151 jdk. 

Any ideas?

**Comment by Robiq** [comment]
Same problem!

**Comment by lekanteto** [comment]
same problem as #651 ?

**Comment by st4ycool** [comment]
Same problem trying to see what p0 contains. Sometimes it's NPE in log and debugger fails, sometimes it's just internal error and debugger fails =(

**Comment by josefst** [comment]
Same problem  using IntelliJ IDEA 2019.2

**Comment by wrobezin** [comment]
Same problem using Android Studios 3.5.2

**Comment by n3tman** [comment]
Android Studio 3.5.3 with smalidea-0.05:

![2020-01-30_162904](https://user-images.githubusercontent.com/16892631/73453842-e6c71080-437d-11ea-8334-59f0d177c060.png)

Variables `v1` and `v2` have been set, but Watcher shows an Internal error.
In most cases it works fine, but here it doesn't.

Stack trace:
```
java.lang.NullPointerException
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:567)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:587)
	at org.jf.dexlib2.analysis.MethodAnalyzer.addPredecessorSuccessor(MethodAnalyzer.java:552)
	at org.jf.dexlib2.analysis.MethodAnalyzer.buildInstructionList(MethodAnalyzer.java:514)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:127)
	at org.jf.smalidea.psi.impl.SmaliMethod.getMethodAnalyzer(SmaliMethod.java:327)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstructionFromMethod(SmaliInstruction.java:199)
	at org.jf.smalidea.psi.impl.SmaliInstruction.getAnalyzedInstruction(SmaliInstruction.java:222)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.wrapContext(SmaliCodeFragmentFactory.java:138)
	at org.jf.smalidea.debugging.SmaliCodeFragmentFactory.createPresentationCodeFragment(SmaliCodeFragmentFactory.java:94)
	at com.intellij.debugger.engine.evaluation.CodeFragmentFactoryContextWrapper.createPresentationCodeFragment(CodeFragmentFactoryContextWrapper.java:49)
	at org.jetbrains.java.debugger.JavaDebuggerEditorsProvider.createExpressionCodeFragment(JavaDebuggerEditorsProvider.java:77)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:67)
	at com.intellij.xdebugger.evaluation.XDebuggerEditorsProviderBase.createDocument(XDebuggerEditorsProviderBase.java:59)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.createDocument(XDebuggerEditorBase.java:347)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.createDocument(XDebuggerExpressionComboBox.java:130)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.doSetText(XDebuggerExpressionComboBox.java:119)
	at com.intellij.xdebugger.impl.ui.XDebuggerEditorBase.setExpression(XDebuggerEditorBase.java:279)
	at com.intellij.xdebugger.impl.ui.XDebuggerExpressionComboBox.<init>(XDebuggerExpressionComboBox.java:59)
	at com.intellij.xdebugger.impl.ui.tree.XDebuggerTreeInplaceEditor.<init>(XDebuggerTreeInplaceEditor.java:47)
	at com.intellij.xdebugger.impl.frame.WatchInplaceEditor.<init>(WatchInplaceEditor.java:42)
	at com.intellij.xdebugger.impl.ui.tree.nodes.WatchesRootNode.editWatch(WatchesRootNode.java:186)
	at com.intellij.xdebugger.impl.frame.actions.XEditWatchAction.perform(XEditWatchAction.java:46)
	at com.intellij.xdebugger.impl.frame.actions.XWatchesTreeActionBase.actionPerformed(XWatchesTreeActionBase.java:62)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:673)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:518)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:681)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by JesusFreke** [comment]
n3tman, can you share the full method that was causing the NPE you mentioned? It looks like the class is from androidx.appcompat.app, so it shouldn't be sensitive.

**Comment by n3tman** [comment]
Sure, but it's not the original code. I was analysing some changes made by other people.
The purpuse, as I found out, is to check if `.apk` signature matches a constant value.
If it doesn't, the app is closed.

Method `L` from the screenshot above:
```smali
.method public static l(Ljava/lang/String;)Ljava/lang/String;
    .locals 11
    const-string v1, ""
    :try_start_0
    new-instance v0, Ljava/lang/String;
    const/4 v2, 0x0
    invoke-static {p0, v2}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B
    move-result-object v2
    const-string v3, "UTF-8"
    invoke-direct {v0, v2, v3}, Ljava/lang/String;-><init>([BLjava/lang/String;)V
    :try_end_0
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0
    :goto_0
    return-object v0
    :catch_0
    move-exception v0
    move-object v0, v1
    goto :goto_0
.end method
```
Which is called by another custom method `loadApplication`
```smali
.method public loadApplication()V
    .locals 2
    invoke-virtual {p0}, Landroidx/appcompat/app/e;->getClass()Ljava/lang/Class;
    move-result-object v0
    invoke-virtual {v0}, Ljava/lang/Class;->getClassLoader()Ljava/lang/ClassLoader;
    move-result-object v0
    const-string v1, "26U="
    invoke-static/range {v1 .. v1}, Landroidx/appcompat/app/e;->l(Ljava/lang/String;)Ljava/lang/String;
    move-result-object v1
    invoke-virtual {v0, v1}, Ljava/lang/ClassLoader;->getResourceAsStream(Ljava/lang/String;)Ljava/io/InputStream;
    move-result-object v0
    if-nez v0, :cond_0
    const/4 v0, 0x0
    invoke-static {v0}, Ljava/lang/System;->exit(I)V
    :cond_0
    return-void
.end method
```
And this method is called inside `onStart`
```smali
.method protected onCreate(Landroid/os/Bundle;)V
    .locals 1
    invoke-virtual {p0}, Landroidx/appcompat/app/e;->getDelegate()Landroidx/appcompat/app/g;
    move-result-object v0
    invoke-virtual {v0}, Landroidx/appcompat/app/g;->e()V
    invoke-virtual {v0, p1}, Landroidx/appcompat/app/g;->a(Landroid/os/Bundle;)V
    invoke-virtual {p0}, Landroidx/appcompat/app/e;->loadApplication()V
    invoke-super {p0, p1}, Landroidx/fragment/app/d;->onCreate(Landroid/os/Bundle;)V
    return-void
.end method
```

**Comment by JesusFreke** [comment]
Thanks, I'll take a look and see if I can reproduce the NPE. I couldn't find anything just by looking at the code, unfortunately.

**Comment by JesusFreke** [comment]
I can't seem to reproduce the NPE unfortunately. I'm able to make a MethodAnalyzer for all 3 of those methods with no problem.

**Comment by ttimasdf** [comment]
I don't remember exactly but I recall there's (maybe) a change in JDWP implementation on Android somewhere between Nouget and Pie, that preventing JDWP client from retrieving local variable information.

**Comment by johnsonshu** [comment]
Same issue, any resolutions ?

**Comment by jackwpa** [comment]
It's been explained on the blog post linked above, from the JEB Decompiler website. Use Android R or anything less or equal than Android O.
Both Android P and Q suffer that issue.

**Comment by GammaRay360** [comment]
> It's been explained on the blog post linked above, from the JEB Decompiler website. Use Android R or anything less or equal than Android O.
> Both Android P and Q suffer that issue.

I have the same issue with android 6.0.1 nexus 5. Debugging with android studio.
Also sometimes, especially with variables p0, p1, p2, the debugger crash when i inspect their value. sometimes the whole process crash and I need to restart the app to debug again.
The "this" reference always works tough
![Screen Shot 2020-05-25 at 12 48 35](https://user-images.githubusercontent.com/10284620/82802066-fb786880-9e86-11ea-8045-7e1e4e356c13.png)

**Comment by n3tman** [comment]
Yeah, I as well noticed that you can restart Android Studio to make some Internal Errors go away.
So whenever I need to explore the registers, I just put one breakpoint, restart the Studio, and it stops and shows them all.
However, after some time you might see these errors again.
Also, it's normal that in some areas of the code you won't be able to stop the execution. The debugger just disconnects itself.
In this case just find some other function (before or after) where you can put a breakpoint. Or use good old logcat debug (print register values there).
