### ISSUE TITLE
baksmali bug: Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1668186019 out of bounds for length 127992

### ISSUE THREAD

**Issue by XopmoH97** [JesusFreke/smali#698]
[AdupsFota.zip](https://github.com/JesusFreke/smali/files/3332204/AdupsFota.zip)
(.odex file in archive)

I tested latest baksmali 2.2.7 and baksmali 2.2.6 on Ubuntu 18.04 and Windows 10. Everywhere repeated error: "java.lang.ArrayIndexOutOfBoundsException: Index 1668186019 out of bounds for length 127992". Android: 9.0 [API: 28].
Detailed information:
`C:\Users\Администратор\Desktop\smali_test>java -jar baksmali-2.2.7.jar d AdupsFota.odex -o AdupsFota
Warning: You are disassembling an odex/oat file without deodexing it. You won't
be able to re-assemble the results unless you deodex it. See "baksmali help
deodex"
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1668186019 out of bounds for length 127992
        at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:77)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:147)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:143)
        at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
        at org.jf.dexlib2.util.SyntheticAccessorResolver.<init>(SyntheticAccessorResolver.java:80)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:288)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
        at org.jf.baksmali.Main.main(Main.java:102)`

Java version on Windows 10:
`C:\Users\Администратор\Desktop\smali_test>java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)`

Java version on Ubuntu 18.04:
`sam@DESKTOP-1C66VG3:~$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)`

How to fix this???

**Comment by JesusFreke** [comment]
This should be fixed by 2.3

**Comment by bphd** [comment]
Same here
