### ISSUE TITLE
Error when deodexing

### ISSUE THREAD

**Issue by Shouri14** [JesusFreke/smali#708]
When I use the following command:
-jar baksmali.jar x services.odex -d framework\arm -o tmp

I keep getting this error:

Error occurred while loading class path files. Aborting.
java.lang.ArrayIndexOutOfBoundsException: 40
        at org.jf.dexlib2.dexbacked.CDexBackedDexFile.isCdex(CDexBackedDexFile.java:67)
        at org.jf.dexlib2.dexbacked.OatFile$OatDexEntry.getDexFile(OatFile.java:571)
        at org.jf.dexlib2.dexbacked.OatFile$OatDexEntry.getDexFile(OatFile.java:559)
        at org.jf.dexlib2.analysis.PathEntryLoader.loadEntry(PathEntryLoader.java:62)
        at org.jf.dexlib2.analysis.ClassPathResolver.loadLocalOrDeviceBootClassPathEntry(ClassPathResolver.java:197)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:89)
        at org.jf.dexlib2.analysis.ClassPathResolver.<init>(ClassPathResolver.java:154)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:131)
        at org.jf.baksmali.AnalysisArguments.loadClassPathForDexFile(AnalysisArguments.java:88)
        at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:209)
        at org.jf.baksmali.DeodexCommand.getOptions(DeodexCommand.java:71)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
        at org.jf.baksmali.Main.main(Main.java:102)

Used baksmali-2.3.jar and smali-2.3.jar

How to fix this?

**Comment by MaemaOver** [comment]
Did you slove this problem?
