### ISSUE TITLE
MissingCommandException

### ISSUE THREAD

**Issue by runo280** [JesusFreke/smali#716]
What is wrong with this command?
I'm installed Java 1.8.
```
$ java -jar baksmali.jar -x SystemUI.odex -d framework/ -o SystemUI
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got -x
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
        at com.beust.jcommander.JCommander.parse(JCommander.java:304)
        at com.beust.jcommander.JCommander.parse(JCommander.java:287)
        at org.jf.baksmali.Main.main(Main.java:90)
```

**Comment by JesusFreke** [comment]
when it doubt, try --help ;)
