### ISSUE TITLE
Can't convert baksmali.jar in .dex

### ISSUE THREAD

**Issue by abrala** [JesusFreke/smali#719]
-- d8 (build 2e75d3f0fe107826c8b0c82a13bb0601f24a7b86 from go/r8bot (slave83-c7))
> Compilation failed with an internal error.
java.lang.IllegalArgumentException
	at com.android.tools.r8.org.objectweb.asm.ClassReader.<init>(ClassReader.java:160)
	at com.android.tools.r8.org.objectweb.asm.ClassReader.<init>(ClassReader.java:143)
	at com.android.tools.r8.org.objectweb.asm.ClassReader.<init>(ClassReader.java:418)
	at com.android.tools.r8.graph.JarClassFileReader.read(JarClassFileReader.java:66)
	at com.android.tools.r8.dex.ApplicationReader$ClassReader.lambda$readClassSources$1(ApplicationReader.java:231)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

-- dx (version 1.16)
> PARSE ERROR:
unsupported class file version 56.0
...while parsing org/jf/baksmali/Adaptors/AnnotationFormatter.class
1 error; aborting

**Comment by JesusFreke** [comment]
This works for me:

    ~/android-sdk/build-tools/28.0.3$ ./d8 --classpath ../../platforms/android-28/android.jar baksmali-2.3.1.jar --output baksmali.zip

**Comment by abrala** [comment]
> This works for me:
> 
> ```
> ~/android-sdk/build-tools/28.0.3$ ./d8 --classpath ../../platforms/android-28/android.jar baksmali-2.3.1.jar --output baksmali.zip
> ```

Didn't work, same error. MacOS Mojave 10.14.6
> $ /Users/daniel/Library/Android/sdk/build-tools/29.0.0/d8 --classpath android.jar smali-2.3.1-dev-fat.jar --output sm.zip
