### ISSUE TITLE
smalidea Throw an error while viewing a variable

### ISSUE THREAD

**Issue by xfxiao** [JesusFreke/smali#734]
java.lang.NullPointerException
	at org.jf.smalidea.debugging.value.LazyObjectReference.disableCollection(LazyObjectReference.java:48)
	at com.intellij.debugger.impl.DebuggerUtilsEx.disableCollection(DebuggerUtilsEx.java:1071)
	at com.intellij.debugger.engine.SuspendContextImpl.keep(SuspendContextImpl.java:191)
	at com.intellij.debugger.impl.DebuggerUtilsEx.keep(DebuggerUtilsEx.java:437)
	at com.intellij.debugger.ui.impl.watch.EvaluationDescriptor.calcValue(EvaluationDescriptor.java:90)
	at com.intellij.debugger.ui.impl.watch.ValueDescriptorImpl.setContext(ValueDescriptorImpl.java:186)
	at com.intellij.debugger.engine.JavaDebuggerEvaluator$1.threadAction(JavaDebuggerEvaluator.java:87)
	at com.intellij.debugger.engine.events.DebuggerContextCommandImpl.contextAction(DebuggerContextCommandImpl.java:83)
	at com.intellij.debugger.engine.events.SuspendContextCommandImpl.action(SuspendContextCommandImpl.java:73)
	at com.intellij.debugger.engine.events.DebuggerCommandImpl.run(DebuggerCommandImpl.java:33)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:147)
	at com.intellij.debugger.engine.DebuggerManagerThreadImpl.processEvent(DebuggerManagerThreadImpl.java:43)
	at com.intellij.debugger.impl.InvokeThread.run(InvokeThread.java:141)
	at com.intellij.debugger.impl.InvokeThread.access$100(InvokeThread.java:18)
	at com.intellij.debugger.impl.InvokeThread$WorkerThreadRequest.run(InvokeThread.java:47)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by xfxiao** [comment]
![image](https://user-images.githubusercontent.com/28923019/68102171-6de62300-ff0c-11e9-8b8a-1393051810df.png)

**Comment by n3tman** [comment]
See here: https://github.com/JesusFreke/smali/issues/691
