### ISSUE TITLE
Help to modify an odex line in linux based device mobile 

### ISSUE THREAD

**Issue by ronmazor** [JesusFreke/smali#752]
<pre>
Exception in thread "main" org.jf.dexlib2.DexFileFactory$UnsupportedOatVersionException: Unsupported oat version: 45
        at org.jf.dexlib2.DexFileFactory.loadDexContainer(DexFileFactory.java:274)
        at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:153)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:162)
        at org.jf.baksmali.Main.main(Main.java:102)
</pre>

**Comment by JesusFreke** [comment]
Yep, L oat files are unsupported :). See, e.g. https://github.com/JesusFreke/smali/issues/644
