### ISSUE TITLE
Support invoke-polymorphic (and -range) as builder instruction

### ISSUE THREAD

**Issue by GraxCode** [JesusFreke/smali#767]
Should not be that hard to implement, see [Signature Polymorphic Methods](https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-2.html#jvms-2.9.3).
```
org.jf.util.ExceptionWithContext: Instruction format Format45cc not supported
	at org.jf.dexlib2.builder.MutableMethodImplementation.convertAndSetInstruction(MutableMethodImplementation.java:675)
	at org.jf.dexlib2.builder.MutableMethodImplementation.<init>(MutableMethodImplementation.java:94)
```
`invoke-polymorphic` can be generated by converting this code with `dx` to dex:
```java
public void invoke(MethodHandle handle) throws Throwable {
    handle.invoke(0, 1);
    handle.invokeExact("args", "here");
}
```

**Comment by vn-ki** [comment]
Hi @JesusFreke, when is the next release planned? Thanks
