### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by paradiseduo** [JesusFreke/smali#781]
```
> java -jar baksmali.jar d -o smali1 0xb3aaa2a0.dex
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1983804987 out of bounds for length 149460
	at org.jf.dexlib2.dexbacked.DexReader.readUleb128(DexReader.java:132)
	at org.jf.dexlib2.dexbacked.DexReader.readSmallUleb128(DexReader.java:119)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:93)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$10.get(DexBackedDexFile.java:465)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$10.get(DexBackedDexFile.java:461)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:210)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:206)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.util.SyntheticAccessorResolver.<init>(SyntheticAccessorResolver.java:80)
	at org.jf.baksmali.DisassembleCommand.getOptions(DisassembleCommand.java:288)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:183)
	at org.jf.baksmali.Main.main(Main.java:102)
```

how to fix this error -_-
[0xb3aaa2a0.dex.zip](https://github.com/JesusFreke/smali/files/5199539/0xb3aaa2a0.dex.zip)

**Comment by zeirew** [comment]
@paradiseduo Hello, did you ever figure out what was going wrong here? I'm getting a very similar error message. 

```
java.lang.ArrayIndexOutOfBoundsException: Index 710104 out of bounds for length 710104
        at org.jf.dexlib2.dexbacked.DexReader.readUleb128(DexReader.java:132)
        at org.jf.dexlib2.dexbacked.DexReader.readSmallUleb128(DexReader.java:119)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$HiddenApiRestrictionsReader$4.readNextItem(DexBackedClassDef.java:658)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$HiddenApiRestrictionsReader$4.readNextItem(DexBackedClassDef.java:655)
        at org.jf.dexlib2.dexbacked.util.VariableSizeListIterator.next(VariableSizeListIterator.java:77)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$5$1.readNextItem(DexBackedClassDef.java:419)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$5$1.readNextItem(DexBackedClassDef.java:404)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
...
```

**Comment by paradiseduo** [comment]
> Reference in ne

没有

**Comment by bphd** [comment]
Same here
