### ISSUE TITLE
smali crashes on Android 11 files when adding additional methods

### ISSUE THREAD

**Issue by jtothe4n** [JesusFreke/smali#782]
On Android 11 when I try to compile files it crashes each time when I add addtional methods to smali files.
It compiles fine when no new methods are added.

> X:\_reverse engineering>java -jar smali.jar assemble coral -o classes_coral.dex
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/collection/LongSparseArray;->clone()Landroidx/collection/LongSparseArray;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1046)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:345)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
        at org.jf.smali.Smali.assemble(Smali.java:131)
        at org.jf.smali.AssembleCommand.run(AssembleCommand.java:96)
        at org.jf.smali.Main.main(Main.java:100)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x12
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1319)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1042)
        ... 5 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65541
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1279)
        ... 6 more

**Comment by fmresearchnovak** [comment]
How many methods are you adding?  There are separately enumerated and indexed constant pools for references to strings, types, fields, and methods. And, the pools have a limited size (I think 65535 items is the limit).  The pools existence is mentioned in the official dalvik bytecode documentation: https://source.android.com/devices/tech/dalvik/dalvik-bytecode

**Comment by jtothe4n** [comment]
It does not matter if 1 or more. Crashes everrytime.
100 % sure that I'm not close to that limit.

**Comment by JesusFreke** [comment]
`Unsigned short value out of range: 65541`

Yes, you are :). There are either too many methods or fields.

**Comment by jtothe4n** [comment]
> `Unsigned short value out of range: 65541`
> 
> Yes, you are :). There are either too many methods, types or call sites. 

Mhhh..so the stock pixel 11 SystemUI.apk has exactly the ushort count of methods. Let me count them.
The limit is per dex right? Might just shift the code to another dex

**Comment by jtothe4n** [comment]
..so I counted 54390 methods and 32912 fields

That's from the december patch, and well it works.
Need to check the september/oct patch again.
Sorry for the trouble, will try to read the full stack and exception next time.

**Comment by JesusFreke** [comment]
`baksmali list methods blah.dex | wc -l` is the number you want to look at.
