### ISSUE TITLE
Baksmali throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Madafaka9609** [JesusFreke/smali#800]
I am trying to decode an .odex file but it throws me this ArrayLimit exception, I have already tried with several versions of baksmali and I cannot decode the .odex file

Here I leave the error that throws me and the command I am using..if you could help me..thanks in advance

sudo java -jar /home/aarom/Downloads/baksmali-2.2.4.jar x toDus\ \(Beta\)/base.odex -d /home/aarom/Desktop/framework/arm64 -b ./framework/arm64/boot.oat -o odex/ 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1630474416 out of bounds for length 3641592
	at org.jf.dexlib2.dexbacked.BaseDexBuffer.readSmallUint(BaseDexBuffer.java:53)
	at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:575)
	at org.jf.dexlib2.dexbacked.OatFile$DexEntryIterator.next(OatFile.java:566)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at org.jf.util.AbstractForwardSequentialList$1.next(AbstractForwardSequentialList.java:91)
	at java.base/java.util.AbstractSequentialList.get(AbstractSequentialList.java:88)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:129)
	at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:149)
	at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:161)
	at org.jf.baksmali.Main.main(Main.java:102)

**Comment by bphd** [comment]
Same here

**Comment by fynch3r** [comment]
Same in baksmali-2.5.2

**Comment by bphd** [comment]
My brother in آدم عليه الصلاة والسلام it's been four years, that Jesus clearly don't give any Freke
