### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by pypygeek** [JesusFreke/smali#823]
## ENVIRONMENT

```
OS and Version: Windows 10 21H1 (Build 19043.1151)
JDK Version: 16.0.2
```

## EXPLANATION OF THE ISSUE

```
Only this file `2f820a64e255e540903e2a51482e8144a8408176a3319ed6977c3c7d9e3678d6.apk` causes the following `returned non-zero exit status 1` error.

[https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1780](url)

```
![128447282-14fd985f-af86-4f5d-9c54-9fc3b25c6390](https://user-images.githubusercontent.com/19469996/128455903-44722459-2d6d-4124-9ee0-df843f3798a6.png)

## LOG FILE

```
[ERROR] 06/Aug/2021 13:17:28 - Error Performing Static Analysis
Traceback (most recent call last):
  File "C:\Users\<username>\Desktop\Mobile-Security-Framework-MobSF-master\mobsf\StaticAnalyzer\views\android\static_analyzer.py", line 215, in static_analyzer
    tracker_res = tracker.get_trackers()
  File "C:\Users\<username>\Desktop\Mobile-Security-Framework-MobSF-master\mobsf\MalwareAnalyzer\views\Trackers.py", line 207, in get_trackers
    trackers = self.detect_trackers()
  File "C:\Users\<username>\Desktop\Mobile-Security-Framework-MobSF-master\mobsf\MalwareAnalyzer\views\Trackers.py", line 183, in detect_trackers
    eclasses = self.get_embedded_classes()
  File "C:\Users\<username>\Desktop\Mobile-Security-Framework-MobSF-master\mobsf\MalwareAnalyzer\views\Trackers.py", line 129, in get_embedded_classes
    classes = subprocess.check_output(
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\<username>\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:/Program Files/Java/jdk-16.0.2/bin/java.exe', '-jar', 'C:/Users/<username>/Desktop/Mobile-Security-Framework-MobSF-master/mobsf/StaticAnalyzer/tools\\baksmali-2.5.2.jar', 'list', 'classes', 'C:/Users/<username>/.MobSF/uploads/a67d6f70d4618133ef362c4eec3c98b2\\secret-classes.dex']' returned non-zero exit status 1.
[ERROR] 06/Aug/2021 13:17:28 - Command '['C:/Program Files/Java/jdk-16.0.2/bin/java.exe', '-jar', 'C:/Users/<username>/Desktop/Mobile-Security-Framework-MobSF-master/mobsf/StaticAnalyzer/tools\\baksmali-2.5.2.jar', 'list', 'classes', 'C:/Users/<username>/.MobSF/uploads/a67d6f70d4618133ef362c4eec3c98b2\\secret-classes.dex']' returned non-zero exit status 1.
[ERROR] 06/Aug/2021 13:17:28 - Internal Server Error: /static_analyzer/
```

**Comment by JesusFreke** [comment]
Can you share the offending apk?

**Comment by ghost** [comment]
@JesusFreke > Can you share the offending apk?

Of course.
Check your Mail please.
