### ISSUE TITLE
services.odex" has no dex files

### ISSUE THREAD

**Issue by elesbb** [JesusFreke/smali#837]
`C:\Users\Seth\APK GUI\Smali>java -jar baksmali.jar x -a 31 -d "D:\Misc\Android Stuff\S20 Plus 5G Stuff\firmwares\SM-G986U_SPR_G986USQU1CUA4_fac\framework\oat\arm64" "D:\Misc\Android Stuff\S20 Plus 5G Stuff\firmwares\SM-G986U_SPR_G986USQU1CUA4_fac\framework\oat\arm64\services.odex"
Exception in thread "main" java.lang.RuntimeException: "D:\Misc\Android Stuff\S20 Plus 5G Stuff\firmwares\SM-G986U_SPR_G986USQU1CUA4_fac\framework\oat\arm64\services.odex" has no dex files
        at org.jf.baksmali.DexInputCommand.loadDexFile(DexInputCommand.java:167)
        at org.jf.baksmali.DisassembleCommand.run(DisassembleCommand.java:162)
        at org.jf.baksmali.Main.main(Main.java:102)`

Samsung Galaxy S20+ 5G on android 11. I am trying to decompile the services to access specifically SemSoftApConfiguration. This class does not exist in the services.jar despite there being a classes.dex inside the jar. There is also .rodata and .text inside the .odex file if opened via 7zip. The classes must exist in this .odex file but baksmali cannot decompile it because of the error presented.

**Comment by JesusFreke** [comment]
If there's a dex in the jar, then why are you trying to deodex the odex?

**Comment by elesbb** [comment]
I was trying to deodex the odex cause of the missing classes. However, I decompiled the entire framework directory and found the "missing" class inside another jar. I apologize for the issue opening.
